### ISSUE TITLE
Unnecessary stack trace in cli error

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1086]
The stack trace in errors like this is unnecessary and makes an innocent error look more scary than it is.

Also since the end user doesn't directly edit that file there's no reason to mention it in the error. A simple message like `Alias 'local' does not exist.` would be all that's required.

```
Error: Alias, local, not found in config file: /Users/kstaken/.teraslice/aliases.yaml
    at new Config (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/lib/config.js:32:23)
    at Object.exports.handler (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/cmds/assets/deploy.js:49:23)
    at Object.runCommand (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/node_modules/yargs/yargs.js:1078:30)
    at Object.runCommand (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/node_modules/yargs/lib/command.js:200:45)
    at Object.parseArgs [as _parseArgs] (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/node_modules/yargs/yargs.js:1078:30)
    at Object.get [as argv] (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/index.js:5:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by kstaken** [comment]
Not a current concern.
