### ISSUE TITLE
data access stacks in errors

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1094]
I'm still getting stack traces in some errors. In this case trying to access an endpoint using a user that hasn't been granted access to it.

```
{"error":"Access Denied","debug":{"timestamp":"2019-04-22T16:46:26.929Z","message":"User \"admin\" is not assigned to a role","stack":"TSError: User \"admin\" is not assigned to a role\n    at ACLManager.getViewForSpace (/Users/kstaken/projects/opensource/teraslice/packages/data-access/dist/src/acl-manager.js:343:19)\n    at spaceErrorHandler (/Users/kstaken/projects/opensource/teraslice/packages/data-access-plugin/dist/src/manager/index.js:134:52)\n    at /Users/kstaken/projects/opensource/teraslice/packages/data-access-plugin/dist/src/utils.js:14:19\n    at app.use (/Users/kstaken/projects/opensource/teraslice/packages/data-access-plugin/dist/src/manager/index.js:133:13)\n    at Layer.handle [as handle_request] (/Users/kstaken/projects/opensource/teraserver/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/kstaken/projects/opensource/teraserver/node_modules/express/lib/router/index.js:317:13)\n    at /Users/kstaken/projects/opensource/teraserver/node_modules/express/lib/router/index.js:284:7\n    at param (/Users/kstaken/projects/opensource/teraserver/node_modules/express/lib/router/index.js:354:14)\n    at param (/Users/kstaken/projects/opensource/teraserver/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/Users/kstaken/projects/opensource/teraserver/node_modules/express/lib/router/index.js:410:3)\n    at next (/Users/kstaken/projects/opensource/teraserver/node_modules/express/lib/router/index.js:275:10)\n    at rootErrorHandler (/Users/kstaken/projects/opensource/teraslice/packages/data-access-plugin/dist/src/manager/index.js:106:17)\n    at <anonymous>","statusCode":403}}
```

**Comment by peterdemartini** [comment]
I thought we discussed this giving show debug information about error if the user is `ADMIN` or higher. Should we make it `SUPERADMIN` only?

**Comment by kstaken** [comment]
Ahh, I forgot about that. This was superadmin. I think this will cause confusion if customer admins get stacks traces so yes should probably restrict to superadmin.
