### ISSUE TITLE
Asset uploads fail when asset has been removed from ES but not disk

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1111]
Asset uploads fail if the asset has:

* already been uploaded
* deleted from ES
* not deleted from disk

You get the error shown below.

I would expect Teraslice to either:

* delete the existing on disk asset and put the new one there
* use the existing but warn the user that it was found on disk already
* at the least if erroring is decided to be the write thing to do, the error condition could be more explicit about what the scenario is.

## Error

```
[2019-06-05T23:25:04.584Z] ERROR: assets_service/93810 on badwater.local: Failure checking asset index, could not get asset with id: 315eebddcdefe5f8b9fa28eb84daf051297ddb36, caused by TSError: invoking elasticsearch-api client->get(), caused by Elasticsearch Error: Not Found (module=assets_service, err.code=ERROR)
    TSError: Failure checking asset index, could not get asset with id: 315eebddcdefe5f8b9fa28eb84daf051297ddb36, caused by TSError: invoking elasticsearch-api client->get(), caused by Elasticsearch Error: Not Found
        at backend.get.then.catch (/Users/godber/Workspace/terascope/opensource/teraslice/packages/teraslice/lib/cluster/storage/assets.js:40:39)
        at tryCatcher (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:690:18)
        at _drainQueueStep (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:138:12)
        at _drainQueue (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:131:9)
        at Async._drainQueues (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:147:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
    	caused by, TSError: invoking elasticsearch-api client->get(), caused by Elasticsearch Error: Not Found
        at _errorHandlerFn (/Users/godber/Workspace/terascope/opensource/teraslice/packages/elasticsearch-api/index.js:531:24)
        at tryCatcher (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:690:18)
        at _drainQueueStep (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:138:12)
        at _drainQueue (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:131:9)
        at Async._drainQueues (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:147:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
    Caused by: TSError: invoking elasticsearch-api client->get(), caused by Elasticsearch Error: Not Found
        at _errorHandlerFn (/Users/godber/Workspace/terascope/opensource/teraslice/packages/elasticsearch-api/index.js:531:24)
        at tryCatcher (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/promise.js:690:18)
        at _drainQueueStep (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:138:12)
        at _drainQueue (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:131:9)
        at Async._drainQueues (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:147:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
    Caused by: Error: Not Found
        at respond (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/elasticsearch/src/lib/transport.js:308:15)
        at checkRespForFailure (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/elasticsearch/src/lib/transport.js:267:7)
        at HttpConnector.<anonymous> (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
        at IncomingMessage.wrapper (/Users/godber/Workspace/terascope/opensource/teraslice/node_modules/lodash/lodash.js:4935:19)
        at IncomingMessage.emit (events.js:194:15)
        at endReadableNT (_stream_readable.js:1125:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by peterdemartini** [comment]
This was fixed a while back (I can't remember when) but the error no longer happens.
