### ISSUE TITLE
In cluster mode if a job errors it consumes the workers and the job can't be stopped

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#116]
I submitted a job that referenced an index that didn't exist. The job threw an error but did not release the workers that it consumed even though it wasn't actually able to run. Submitting a new job then hangs with the master logging repeatedly.

```
{"name":"teraslice","hostname":"kteramac.local","pid":49531,"level":30,"msg":" There are not enough workers available, job is enqueued","time":"2016-03-30T22:47:48.187Z","v":0}
```

That also resulted in the post request for the new job hanging until it eventually just exits with no response.

```
curl -XPOST localhost:5678/job -d @../examples/jobs/data_generator.json
curl: (52) Empty reply from server
```
After that response the master continues to log as above.

Attempting to stop the job appears to fail.

```
curl -XPOST localhost:5678/job/8ee6575e-5208-4bf4-9af8-b2b944a28cd0/?action=stop
No active job was found with the provided id: 8ee6575e-5208-4bf4-9af8-b2b944a28cd0
 the job may have finished or the id provided was incorrect
```

**Comment by kstaken** [comment]
The error on Stopping the job is because the PR for terafoundation hasn't been merged yet.

**Comment by kstaken** [comment]
I think this is another example of this problem. The job tries to start but the index doesn't exist and the worker dies but not in a controlled fashion that updates the job.

```
teraslice-worker_1 | Unhandled rejection Error: Could not retrieve start date for index: Error: IndexMissingException[[example-logs] missing]
teraslice-worker_1 |     at /app/source/lib/utils/elastic_utils.js:275:15
teraslice-worker_1 |     at bound (domain.js:287:14)
teraslice-worker_1 |     at runBound (domain.js:300:12)
teraslice-worker_1 |     at tryCatcher (/app/source/node_modules/bluebird/js/main/util.js:26:23)
teraslice-worker_1 |     at Promise._settlePromiseFromHandler (/app/source/node_modules/bluebird/js/main/promise.js:507:31)
teraslice-worker_1 |     at Promise._settlePromiseAt (/app/source/node_modules/bluebird/js/main/promise.js:581:18)
teraslice-worker_1 |     at Promise._settlePromises (/app/source/node_modules/bluebird/js/main/promise.js:697:14)
teraslice-worker_1 |     at Async._drainQueue (/app/source/node_modules/bluebird/js/main/async.js:123:16)
teraslice-worker_1 |     at Async._drainQueues (/app/source/node_modules/bluebird/js/main/async.js:133:10)
teraslice-worker_1 |     at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/bluebird/js/main/async.js:15:14)
teraslice-worker_1 |     at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by kstaken** [comment]
This issue still exists in the latest PR. This is the result of running a job where the index doesn't exist. It crashes and leaves all the workers that were allocated consumed.
```
Unhandled rejection Error: Error on slicer initialization: Error: Could not retrieve start date for index: [index_not_found_exception] no such index, with { resource.type=index_or_alias resource.id=example-logs index=example-logs } :: {"path":"/example-logs/_search","query":{"size":1},"body":"{\"sort\":[{\"created\":{\"order\":\"asc\"}}]}","statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"example-logs\",\"index\":\"example-logs\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"example-logs\",\"index\":\"example-logs\"},\"status\":404}"}
    at /Users/kstaken/projects/opensource/teraslice/lib/cluster/slicer.js:165:23
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at tryCatcher (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
