### ISSUE TITLE
Master crash when pausing a job

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#117]
Started a persistent job to generate sample data then tried to pause it. Resulted in the cluster_master crashing.

```
{"name":"teraslice","hostname":"kteramac.local","pid":49762,"level":30,"msg":"Worker: 10.0.1.8__4 , pid: 49762 has processed: 5000 time completion 2389,3,417 size: 5000,10000,2","time":"2016-03-30T22:57:33.639Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":49737,"level":50,"msg":"Error in master with pid: 49737","time":"2016-03-30T22:57:34.625Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":49737,"level":50,"msg":"Cannot read property 'state' of undefined","time":"2016-03-30T22:57:34.625Z","v":0}
{"name":"teraslice","hostname":"kteramac.local","pid":49737,"level":50,"msg":"TypeError: Cannot read property 'state' of undefined\n    at sendProcessMessage (/Users/kstaken/projects/opensource/teraslice/lib/utils/config.js:672:28)\n    at /Users/kstaken/projects/opensource/teraslice/lib/cluster/master.js:96:13\n    at Array.forEach (native)\n    at Socket.<anonymous> (/Users/kstaken/projects/opensource/teraslice/lib/cluster/master.js:95:22)\n    at Socket.Emitter.emit (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/node_modules/component-emitter/index.js:131:20)\n    at Socket.onevent (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/lib/socket.js:263:10)\n    at Socket.onpacket (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/lib/socket.js:221:12)\n    at Manager.<anonymous> (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)\n    at Manager.Emitter.emit (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/node_modules/component-emitter/index.js:131:20)\n    at Manager.ondecoded (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/lib/manager.js:333:8)\n    at Decoder.<anonymous> (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)\n    at Decoder.Emitter.emit (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)\n    at Decoder.add (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:247:12)\n    at Manager.ondata (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/lib/manager.js:323:16)\n    at Socket.<anonymous> (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)\n    at Socket.Emitter.emit (/Users/kstaken/projects/opensource/teraslice/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/component-emitter/index.js:134:20)","time":"2016-03-30T22:57:34.627Z","v":0}
kteramac:teraslice kstaken$ {"name":"teraslice","hostname":"kteramac.local","pid":49746,"level":30,"msg":"node kteramac.local has disconnected","time":"2016-03-30T22:57:35.250Z","v":0}
```

**Comment by kstaken** [comment]
I think this is resolved with the refactor.
