### ISSUE TITLE
Second job submission fails

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#119]
I started a persistent job then tried to submit a once job while the first job was still running. This is the result from the curl post command. The cluster_master didn't log anything and the already running job continued.

Stopping the cluster then resubmitting via the same command worked fine.

```
$ curl -XPOST localhost:5678/job -d @../examples/jobs/reindex.json
TypeError: Cannot read property &#39;hostname&#39; of undefined<br> &nbsp; &nbsp;at distributeJob (/Users/kstaken/projects/opensource/teraslice/lib/utils/cluster.js:114:57)<br> &nbsp; &nbsp;at /Users/kstaken/projects/opensource/teraslice/lib/cluster/cluster_master.js:61:13<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/kstaken/projects/opensource/teraslice/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/Users/kstaken/projects/opensource/teraslice/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/Users/kstaken/projects/opensource/teraslice/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/kstaken/projects/opensource/teraslice/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /Users/kstaken/projects/opensource/teraslice/node_modules/express/lib/router/index.js:277:22<br> &nbsp; &nbsp;at Function.process_params (/Users/kstaken/projects/opensource/teraslice/node_modules/express/lib/router/index.js:330:12)<br> &nbsp; &nbsp;at next (/Users/kstaken/projects/opensource/teraslice/node_modules/express/lib/router/index.js:271:10)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/Users/kstaken/projects/opensource/teraslice/lib/cluster/cluster_master.js:24:9)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:104:17)<br> &nbsp; &nbsp;at _stream_readable.js:908:16<br> &nbsp; &nbsp;at process._tickDomainCallback (node.js:381:11)
```

**Comment by kstaken** [comment]
This is fixed in the jobs service / cluster service refactor
