### ISSUE TITLE
Error thrown on slice retry

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1192]
Getting this on what I assume is a slice retry. Source of what's causing the retry is currently unknown.

```
TSError: Cannot read property 'length' of undefined\n    at pRetry (/app/source/packages/utils/dist/src/promises.js:43:21), caused by TSError: Cannot read property 'length' of undefined\n    at pRetry (/app/source/packages/utils/dist/src/promises.js:43:21), caused by TSError: Cannot read property 'length' of undefined\n    at pRetry (/app/source/packages/utils/dist/src/promises.js:43:21), caused by TSError: Cannot read property 'length' of undefined\n    at Object.pRetry (/app/source/packages/utils/dist/src/promises.js:43:21
```

**Comment by kstaken** [comment]
This was a bug in a processor.
