### ISSUE TITLE
Improved stack trace on a failed slice

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1213]
When placing the stack trace on a failed slice, it should use the `TSError` to resolve any `causedBy` error so the error can be as descriptive as possible.

**Comment by peterdemartini** [comment]
Ref #1192

**Comment by godber** [comment]
We've been able to reproduce this in a test environment.

Is this what you've fixed?

```
[2019-07-11T21:56:05.093Z] FATAL: worker/8 on ts-wkr-k8s-rc1-snapshot-data-load-10b-0a6aea0a-43d0-7d448cbw6ws: worker received an unhandledRejection, exiting in 300000ms... (modu
le=worker:shutdown_handler, err.code=INTERNAL_SERVER_ERROR)
    TSError: bulk sender error, caused by TSError: invoking elasticsearch-api client->bulk(), caused by Error: Request Timeout after 120000ms
        at _clientRequest.then.catch (/app/source/packages/elasticsearch-api/index.js:253:39)
        at tryCatcher (/app/source/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/source/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/app/source/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/app/source/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/app/source/node_modules/bluebird/js/release/promise.js:690:18)
        at _drainQueueStep (/app/source/node_modules/bluebird/js/release/async.js:138:12)
        at _drainQueue (/app/source/node_modules/bluebird/js/release/async.js:131:9)
        at Async._drainQueues (/app/source/node_modules/bluebird/js/release/async.js:147:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        caused by, TSError: invoking elasticsearch-api client->bulk(), caused by Error: Request Timeout after 120000ms
        at _errorHandlerFn (/app/source/packages/elasticsearch-api/index.js:531:24)
        at tryCatcher (/app/source/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/source/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/app/source/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/app/source/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/app/source/node_modules/bluebird/js/release/promise.js:690:18)
        at _drainQueueStep (/app/source/node_modules/bluebird/js/release/async.js:138:12)
        at _drainQueue (/app/source/node_modules/bluebird/js/release/async.js:131:9)
        at Async._drainQueues (/app/source/node_modules/bluebird/js/release/async.js:147:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        caused by, Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:355:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:384:7)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)
    Caused by: TSError: invoking elasticsearch-api client->bulk(), caused by Error: Request Timeout after 120000ms
        at _errorHandlerFn (/app/source/packages/elasticsearch-api/index.js:531:24)
        at tryCatcher (/app/source/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/source/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/app/source/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/app/source/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/app/source/node_modules/bluebird/js/release/promise.js:690:18)
        at _drainQueueStep (/app/source/node_modules/bluebird/js/release/async.js:138:12)
        at _drainQueue (/app/source/node_modules/bluebird/js/release/async.js:131:9)
        at Async._drainQueues (/app/source/node_modules/bluebird/js/release/async.js:147:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        caused by, Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:355:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:384:7)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)
    Caused by: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:355:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:384:7)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)
```
