### ISSUE TITLE
Job won't schedule and crashes cluster master

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1290]
Trying to run a simple example job locally I'm getting the error below. Appears to crash the cluster master.

Here's the job
```
{
    "name": "Import Data",
    "lifecycle": "once",
    "workers": 1,
    "assets": [
        "file-assets",
        "elasticsearch"
    ],
    "operations": [
        {
            "_op": "file_reader",
            "format": "csv",
            "path": "/tmp/todos",
            "fields": [
                "todo",
                "completed",
                "due"
            ],
            "remove_header": true
        },
        {
            "_op": "elasticsearch_index_selector",
            "type": "todo",
            "index": "todo-list"
        },
        {
            "_op": "elasticsearch_bulk"
        }
    ]
}

```

And the error

```
[2019-08-01T00:35:20.935Z]  INFO: cluster_master/51918 on kmacbook5.local: Scheduling execution: b5d1f3f9-d1c1-4a05-9aad-0adf3dd4107b (module=execution_service, worker_id=GM0RhVUVz, assignment=cluster_master)
[2019-08-01T00:35:20.937Z] FATAL: cluster_master/51918 on kmacbook5.local: cluster_master received an uncaughtException, exiting in 8000ms... (module=cluster_master:shutdown_handler, worker_id=GM0RhVUVz, assignment=cluster_master)
    TypeError: setExecutionStatus(...).then(...).catch(...).finally is not a function
        at allocator (/Users/kstaken/projects/opensource/teraslice/packages/teraslice/lib/cluster/services/execution.js:440:29)
        at Timeout.setInterval [as _onTimeout] (/Users/kstaken/projects/opensource/teraslice/packages/teraslice/lib/cluster/services/execution.js:479:25)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
[2019-08-01T00:35:20.939Z]  INFO: cluster_master/51918 on kmacbook5.local: cluster_master is shutting down (module=cluster_master, worker_id=GM0RhVUVz, assignment=cluster_master)
[2019-08-01T00:35:20.941Z]  INFO: cluster_master/51918 on kmacbook5.local: shutting down (module=execution_service, worker_id=GM0RhVUVz, assignment=cluster_master)
[2019-08-01T00:35:20.942Z]  INFO: cluster_master/51918 on kmacbook5.local: shutting down. (module=job_storage, worker_id=GM0RhVUVz, assignment=cluster_master)
[2019-08-01T00:35:20.942Z]  INFO: cluster_master/51918 on kmacbook5.local: shutting down (module=api_service, worker_id=GM0RhVUVz, assignment=cluster_master)
[2019-08-01T00:35:20.946Z]  WARN: cluster_master/51918 on kmacbook5.local: marking execution ex_id: b5d1f3f9-d1c1-4a05-9aad-0adf3dd4107b, job_id: 62fb4e09-7038-47be-a984-003067e7f1df as terminated (module=execution_service, worker_id=GM0RhVUVz, assignment=cluster_master)
[2019-08-01T00:35:20.995Z] ERROR: cluster_master/51918 on kmacbook5.local: Cannot update terminal job status of "failed" to "terminated" (module=execution_service, worker_id=GM0RhVUVz, assignment=cluster_master, err.code=UNPROCESSABLE_ENTITY)
    TSError: Cannot update terminal job status of "failed" to "terminated"
        at getStatus.then (/Users/kstaken/projects/opensource/teraslice/packages/teraslice/lib/cluster/storage/execution.js:98:35)
        at <anonymous>
    Caused by: Cannot update terminal job status of "failed" to "terminated"
[2019-08-01T00:35:20.995Z]  INFO: cluster_master/51918 on kmacbook5.local: native clustering shutting down (module=native_cluster_service, worker_id=GM0RhVUVz, assignment=cluster_master)
[2019-08-01T00:35:20.999Z]  INFO: teraslice/51916 on kmacbook5.local: node has disconnected from: http://127.0.0.1:5678 (module=node_master)
[2019-08-01T00:35:21.102Z]  INFO: cluster_master/51918 on kmacbook5.local: shutting down. (module=ex_storage, worker_id=GM0RhVUVz, assignment=cluster_master)
[2019-08-01T00:35:21.103Z]  INFO: cluster_master/51918 on kmacbook5.local: cluster_master shutdown took 166ms (module=cluster_master:shutdown_handler, worker_id=GM0RhVUVz, assignment=cluster_master)
[2019-08-01T00:35:22.129Z]  INFO: teraslice/51916 on kmacbook5.local: cluster_master has exited, id: 1, code: 1, signal: null
[2019-08-01T00:35:22.132Z]  INFO: teraslice/51916 on kmacbook5.local: launching a new cluster_master, id: 3
[
```

**Comment by peterdemartini** [comment]
I can fix that tomorrow.
