### ISSUE TITLE
Teraslice master restart triggers job shutdown

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1461]
We were restarting a Teraslice master node to change the connectors in the config file and it restarted about 50% of the running jobs.  This is standard procedure, we restart masters frequently for this sort of update and for teraslice version upgrades.

We will try another restart at some point and get back to you if it happens again.  If this is really happening regularly it's an issue.

**Comment by godber** [comment]
Here are example logs for a single EXID

```
[2019-10-02T18:05:25.135Z]  INFO: cluster_master/19 on teraslice-master: execution 03580000-0000-0000-0000-000000000000 is connected (module=kubernetes_cluster_service, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:05:25.973Z]  INFO: cluster_master/19 on teraslice-master: client 03580000-0000-0000-0000-000000000000 disconnected { reason: 'transport close' } (module=messaging:server, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:08:04.370Z]  INFO: cluster_master/19 on teraslice-master: client 03580000-0000-0000-0000-000000000000 reconnected (module=messaging:server, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:08:04.417Z] ERROR: cluster_master/19 on teraslice-master: terminal error for execution: 03580000-0000-0000-0000-000000000000, shutting down execution, caused by Execution 03580000-0000-0000-0000-000000000000 was starting in running status sending execution:finished event to cluster master (module=execution_service, worker_id=ZXXXXXXXX, assignment=cluster_master, err.code=INTERNAL_SERVER_ERROR)
    TSError: terminal error for execution: 03580000-0000-0000-0000-000000000000, shutting down execution, caused by Execution 03580000-0000-0000-0000-000000000000 was starting in running status sending execution:finished event to cluster master
        at finishExecution (/app/source/packages/teraslice/lib/cluster/services/execution.js:151:27)
        at Server.on (/app/source/packages/teraslice-messaging/dist/src/cluster-master/server.js:60:13)
        at Server.emit (events.js:198:13)
        at Server.emit (/app/source/packages/teraslice-messaging/dist/src/messenger/core.js:107:15)
        at handleResponse (/app/source/packages/teraslice-messaging/dist/src/cluster-master/server.js:65:18)
        at Socket.socket.on (/app/source/packages/teraslice-messaging/dist/src/messenger/core.js:58:39)
        at Socket.emit (events.js:198:13)
        at /app/source/node_modules/socket.io/lib/socket.js:503:12
        at process._tickCallback (internal/process/next_tick.js:61:11)
    Caused by: Execution 03580000-0000-0000-0000-000000000000 was starting in running status sending execution:finished event to cluster master
[2019-10-02T18:08:04.429Z]  INFO: cluster_master/19 on teraslice-master: client 03580000-0000-0000-0000-000000000000 disconnected { reason: 'client namespace disconnect' } (module=messaging:server, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:08:04.436Z]  INFO: cluster_master/19 on teraslice-master: k8s._deleteObjByExId: 03580000-0000-0000-0000-000000000000 execution_controller services deleting: ts-exc-job1 (module=kubernetes_cluster_service, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:08:04.447Z]  INFO: cluster_master/19 on teraslice-master: k8s._deleteObjByExId: 03580000-0000-0000-0000-000000000000 execution_controller jobs deleting: ts-exc-job1 (module=kubernetes_cluster_service, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:08:04.452Z]  INFO: cluster_master/19 on teraslice-master: k8s._deleteObjByExId: 03580000-0000-0000-0000-000000000000 worker deployments deleting: ts-wkr-job1 (module=kubernetes_cluster_service, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:09:23.365Z] ERROR: cluster_master/19 on teraslice-master: Could not find active slicer for ex_id: 03580000-0000-0000-0000-000000000000 (module=api_service, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:09:24.427Z] ERROR: cluster_master/19 on teraslice-master: Could not find active slicer for ex_id: 03580000-0000-0000-0000-000000000000 (module=api_service, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:19:23.578Z] ERROR: cluster_master/19 on teraslice-master: Could not find active slicer for ex_id: 03580000-0000-0000-0000-000000000000 (module=api_service, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:19:24.593Z] ERROR: cluster_master/19 on teraslice-master: Could not find active slicer for ex_id: 03580000-0000-0000-0000-000000000000 (module=api_service, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:29:23.221Z] ERROR: cluster_master/19 on teraslice-master: Could not find active slicer for ex_id: 03580000-0000-0000-0000-000000000000 (module=api_service, worker_id=ZXXXXXXXX, assignment=cluster_master)
[2019-10-02T18:29:24.383Z] ERROR: cluster_master/19 on teraslice-master: Could not find active slicer for ex_id: 03580000-0000-0000-0000-000000000000 (module=api_service, worker_id=ZXXXXXXXX, assignment=cluster_master)

```

**Comment by godber** [comment]
We haven't seen this issue for quite some time, I think the MR above resolved the issue.
