### ISSUE TITLE
Promise rejection on worker allocation

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#156]
Testing in a docker environment with 1 master + 3 worker nodes. Job submission generates this error when allocating workers.

```
Unhandled rejection RangeError: Input array must contain at least 1 items but contains only 0 items
    at SomePromiseArray._getRangeError (/app/src/node_modules/bluebird/js/main/some.js:98:12)
    at SomePromiseArray._resolveEmptyArray (/app/src/node_modules/bluebird/js/main/some.js:102:23)
    at SomePromiseArray.init (/app/src/node_modules/bluebird/js/main/promise_array.js:66:18)
    at SomePromiseArray._init (/app/src/node_modules/bluebird/js/main/some.js:26:10)
    at SomePromiseArray.init (/app/src/node_modules/bluebird/js/main/some.js:37:10)
    at some (/app/src/node_modules/bluebird/js/main/some.js:112:9)
    at Function.Promise.some (/app/src/node_modules/bluebird/js/main/some.js:117:12)
    at allocateWorkers (/app/src/lib/cluster/services/cluster.js:293:24)
    at EventEmitter._.debounce.leading (/app/src/lib/cluster/services/cluster.js:328:13)
    at complete (/app/src/node_modules/lodash/index.js:7697:25)
    at delayed [as _onTimeout] (/app/src/node_modules/lodash/index.js:7707:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by kstaken** [comment]
When this happened the worker did allocate but the node also reported starting 1 slicer & 7 workers all on a single node. The job defines only 1 worker.
