### ISSUE TITLE
teraslice assets issue on ES 6

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1626]
Attempting to register a job with Teraslice on ES 6.8.5 results in the following error.

```
Failure to get assets, caused by TSError: Elasticsearch Error: [illegal_argument_exception] request [/teracluster2__assets/_search] contains unrecognized parameter: [_sourceInclude] -> did you mean any of [_source_include, _source_includes, _source_exclude, _source_excludes]?
    at _errorHandlerFn (/Users/kstaken/projects/opensource/teraslice/packages/elasticsearch-api/index.js:630:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Caused by: Elasticsearch Error: [illegal_argument_exception] request [/teracluster2__assets/_search] contains unrecognized parameter: [_sourceInclude] -> did you mean any of [_source_include, _source_includes, _source_exclude, _source_excludes]?
```

**Comment by kstaken** [comment]
Setting `apiVersion: '6.5'` will hide this error.
