### ISSUE TITLE
teraslice-cli assets deploy does not pull prerelease if explicitly requested

### ISSUE THREAD

**Issue by briend** [terascope/teraslice#1633]
```
teraslice-cli assets deploy myTS terascope/file-assets@0.11.3
Unable to download terascope/file-assets@0.11.3 asset: Error: Error downloading terascope/file-assets@0.11.3: Error: could not find a release for terascope/file-assets (darwin x64)
    at GithubAsset.download (/usr/local/lib/node_modules/teraslice-cli/dist/src/helpers/github-asset.js:49:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I believe it's intentionally skipping drafts and prereleases:

https://github.com/terascope/teraslice/blob/master/packages/teraslice-cli/src/helpers/github-asset.ts#L38-L39

Maybe a force option to override this makes sense?

**Comment by godber** [comment]
I think the spot you found is a good place to start.  I don't think we want a force, I think what I described internally is the desired behavior:

```
Here's how it should work:

earl assets deploy ts-test1 terascope/file-assets

does not specify a version, so the question is, what version should it provide you?  Github has a "release" mechanism that allows you to answer that question, by indicating the "Latest Release" here:

https://github.com/terascope/file-assets/releases

That is the "default" or latest stable release.

If a user explicitly specifies a version of an asset, the user should get that version, regardless of its status on the releases page.
```

I suspect we just didn't think through this case when implementing that helper.  Though perhaps I'm wrong about the desired behavior.

**Comment by godber** [comment]
We should just remove that the draft and prerelease constraints in the case that version is specified.

**Comment by godber** [comment]
The latest version in NPM:

```
npm install -g -u teraslice-cli
...
+ teraslice-cli@0.14.1
updated 3 packages in 22.651s
```

 now has this fix:

```
# specifying an unreleased version works
earl assets deploy ts-minikube-dev1 terascope/elasticsearch-assets@v1.7.1
Downloading terascope/elasticsearch-assets@v1.7.1...
elasticsearch-v1.7.1-... Asset posted to ts-minikube-dev1: 599c89138094fec15d53459abbc0d52c3f804784

# default still gives the latest release
earl assets deploy ts-minikube-dev1 terascope/elasticsearch-assets
Downloading terascope/elasticsearch-assets@v1.6.2...

Asset posted to ts-minikube-dev1: 0813c035327bcb35d505bd03ff032fb75c80d279
```

Thanks Jared.
