### ISSUE TITLE
Error on job start 

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#168]
This gets dumped to stderr. It's running under docker on a real host and hostname lookup logic doesn't work right in this environment.

```
Unhandled rejection TypeError: Cannot read property 'match' of undefined
    at makeHostName (/app/src/lib/utils/cluster.js:17:18)
    at /app/src/lib/cluster/worker.js:30:20
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/app/src/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/src/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/app/src/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/app/src/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/app/src/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/src/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/src/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by kstaken** [comment]
This is fixed but there will need to be further attention paid to hostname handling.
