### ISSUE TITLE
Error when elasticsearch gets saturated

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#172]
I tried running a job with 20 workers and stderr was saturated with the error below. When this happened the whole system seems to fall over with cluster_manager not responding to http requests and nothing showing in the normal teraslice logs.

I think this is the result of state logging occurring at too high of a pace and elasticsearch can't keep up. The job that was running was a sparse index with long stretches of no data so the slices are processed pretty rapid fire.

```
Unhandled rejection Error: RemoteTransportException[[c3b12s1.ndagri.com][inet[/172.17.0.8:9300]][indices:data/write/index]]; nested: EsRejectedExecutionException[rejected execution (queue capacity 200) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1@4a8a62af];
    at respond (/app/source/node_modules/terafoundation/node_modules/elasticsearch/src/lib/transport.js:264:15)
    at checkRespForFailure (/app/source/node_modules/terafoundation/node_modules/elasticsearch/src/lib/transport.js:223:7)
    at keepAliveConnector.<anonymous> (/app/source/node_modules/terafoundation/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/app/source/node_modules/terafoundation/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

**Comment by kstaken** [comment]
This was blowing up the indexing queue because the 3 node state cluster only had 1 shard for the __state index. Bulk requests would help tremendously here.

**Comment by kstaken** [comment]
Correction: looks like it was blowing up on storing the analytics.

**Comment by kstaken** [comment]
Good progress in this area so closing. We'll additional issues on more specific tickets.
