### ISSUE TITLE
teraslice fails to write to SSL encrypted kafka brokers

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1868]
In at least certain configurations, teraslice versions [v0.63.4](https://github.com/terascope/teraslice/releases/tag/v0.63.4) or greater will not produce to ssl encrypted brokers.

**Comment by godber** [comment]
If you encounter this issue, you will see this error mesage in your Teraslice worker logs:

```
    Error: Failed to connect, caused by error: broker transport failure, code: -195, desc: "Broker transport failure"
        at _client.connect (/app/assets/69ff0a23c861b4324f6e5e3a3809bb1ced6144b9/dist/_kafka_clients/base-client.js:74:45)
        at next (/app/node_modules/node-rdkafka/lib/client.js:134:7)
        at /app/node_modules/node-rdkafka/lib/client.js:165:9
```

**Comment by godber** [comment]
This is likely omitting a dependency like `cyrus-sasl-dev` in our base image.

**Comment by godber** [comment]
The `v0.64.5` release is confirmed to fix this.
