### ISSUE TITLE
job start up errors in kubernetes

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1953]
We have an internal process that runs approximately 50 teraslice jobs over the course of 7 minutes periodically.  In release [`v0.64.2`](https://github.com/terascope/teraslice/releases/tag/v0.64.2) I changed how jobs start up.  This release and later results in a higher rate of failed job start ups than prior to this release so the internal cluster that runs the periodic workload cannot be upgraded.  I don't have any details beyond that at the moment.

I either need to revert the k8s job start up changes in `v0.64.2`, which successfully eliminated the 2 minute worker startup problem or address the new unknown job startup failures.  I think there are options for the later.

**Comment by godber** [comment]
This problem does not appear to be present in `v0.66.0`.  I will leave this open a little bit, I still think there's something here.  The one problem that I have seen in the `v0.66.0` (as well as other releases is)

```
TSError: slicer for ex 85d2e4... had an error, shutting down execution, caused by Error: No workers have connected to slicer in the allotted time: 10m
    at ExecutionController._terminalError (/app/source/packages/teraslice/lib/workers/execution-controller/index.js:322:23)
    at Timeout.workerConnectTimeoutId.setTimeout (/app/source/packages/teraslice/lib/workers/execution-controller/index.js:965:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Caused by: Error: No workers have connected to slicer in the allotted time: 10m
    at ExecutionController._startWorkConnectWatchDog (/app/source/packages/teraslice/lib/workers/execution-controller/index.js:949:21)
    at ExecutionController.run (/app/source/packages/teraslice/lib/workers/execution-controller/index.js:251:14)
    at Service.run (/app/source/packages/teraslice/worker-service.js:48:30)
    at Promise.resolve.then.then (/app/source/packages/teraslice/worker-service.js:82:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

And from investigating master logs in one of these cases, the master didn't appear to even try to create the Worker deployment.

**Comment by godber** [comment]
This is such ancient news and hasn't repeated to my knowledge, closing.
