### ISSUE TITLE
Error in worker hangs worker

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#240]
I've seen two occurrences today of worker errors where the worker just hangs and doesn't exit until it is forced to exit.

The first was a job using the API reader to transfer data from a remote site. The network connection dropped but the worker never errored and shutting down teraslice showed the worker was stuck in processing state. 

The second occurrence generated the following log. The underlying ES issue is well known but the worker didn't exit cleanly after throwing this error which is a problem.

```
Unhandled rejection Error: [query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [19970]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.
    at respond (/Users/kstaken/projects/opensource/teraslice/node_modules/terafoundation/node_modules/elasticsearch/src/lib/transport.js:264:15)
    at checkRespForFailure (/Users/kstaken/projects/opensource/teraslice/node_modules/terafoundation/node_modules/elasticsearch/src/lib/transport.js:223:7)
    at keepAliveConnector.<anonymous> (/Users/kstaken/projects/opensource/teraslice/node_modules/terafoundation/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/kstaken/projects/opensource/teraslice/node_modules/terafoundation/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

**Comment by jsnoble** [comment]
instances checking:

- [ ] error on module loading when it does exist
- [ ] error on reader/processor loading
- [ ] error on reader/processor execution
- [ ] make sure state of slice if properly communicated on errored worker
