### ISSUE TITLE
Job status is running when k8s node running execution controller pod dies

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#2673]
When the kubernetes node running an execution controller for a job dies, that job is left in the running state, calling stop on the job doesn't work (the execution controller pod gets stuck in terminating).  Force deleting the execution controller pod will remove the pod and then the job will go to the failed or stopped state.  Or something close to that.  We need to add some sort of execution controller watchdog capability to the k8s cluster master.  This was present in native clustering.

**Comment by godber** [comment]
You might be able to reproduce as follows:

> One specific example that is easily reproducible is use the es reader to read from an index that doesn't exist. The job will get stuck in initializing.

**Comment by godber** [comment]
The example above is a little weak since there are scenarios where a missing index isn't necessarily an error condition.

Despite that. what we are looking for here is ANY scenario where the job tries to start and the execution controllers and workers experience a terminal error and the job doesn't get put into the `failed` state.  I think we have a number of conditions where this is possible.

**Comment by godber** [comment]
Maybe we can write an asset that deliberately generates errors in different parts of the slicer, or fetcher or wherever.

**Comment by sotojn** [comment]
I decided to try testing out using a job that reads into a non existent index and writes it into a new index:

```json
{
    "name": "failing-job",
    "lifecycle": "persistent",
    "workers": 2,
    "assets": [
        "elasticsearch"
    ],
    "operations": [
        {
            "_op": "elasticsearch_reader",
            "index": "joseph_index",
            "date_field_name": "created"
        },
        {
            "_op": "elasticsearch_bulk",
            "size": 10000,
            "index": "joseph_index2"
        }
    ]
}
``` 

Here is the results after running the job for a couple seconds:

Command: `earl ex list localhost `

```
 name         lifecycle   slicers  workers  _status  ex_id                                 job_id                                _created                  _updated                 
 failing-job  persistent  1        2        failed   de64394f-b32d-4680-90a0-5b7ae6e7b386  e2566fb1-963b-45a8-801e-07aeec18736d  2024-06-03T15:42:54.724Z  2024-06-03T15:43:03.718Z 
```

Command: `kubectl get all -n ts-dev1 `

```
NAME                                                    READY   STATUS      RESTARTS   AGE
pod/teraslice-master-67f49bfd75-s92bd                   1/1     Running     0          2d17h
pod/ts-exc-failing-job-e2566fb1-963b-2z7bb              0/1     Completed   0          56m
pod/ts-wkr-failing-job-e2566fb1-963b-5877cb4b56-7fsmd   1/1     Running     0          56m
pod/ts-wkr-failing-job-e2566fb1-963b-5877cb4b56-ljfhb   1/1     Running     0          56m

NAME                       TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/teraslice-master   NodePort   10.96.247.67   <none>        5678:30678/TCP   2d17h

NAME                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/teraslice-master                   1/1     1            1           2d17h
deployment.apps/ts-wkr-failing-job-e2566fb1-963b   2/2     2            2           56m

NAME                                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/teraslice-master-67f49bfd75                   1         1         1       2d17h
replicaset.apps/ts-wkr-failing-job-e2566fb1-963b-5877cb4b56   2         2         2       56m

NAME                                         COMPLETIONS   DURATION   AGE
job.batch/ts-exc-failing-job-e2566fb1-963b   1/1           18s        56m
```

Command: `kubectl -n ts-dev1 logs pod/ts-exc-failing-job-e2566fb1-963b-2z7bb | bunyan`

```
[2024-06-03T15:43:03.844Z] ERROR: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: Teraslice Worker shutting down due to failure! (assignment=execution_controller, err.code=NOT_FOUND)
    TSError: index specified in reader does not exist
        at /app/assets/71da69e118c73b7fdbf6ccee9278b9fa0ea29582/index.js:343751:43
        at async ElasticsearchReaderClient2.verify (/app/assets/71da69e118c73b7fdbf6ccee9278b9fa0ea29582/index.js:344641:9)
        at async ElasticsearchReaderAPI3.makeDateSlicerRanges (/app/assets/71da69e118c73b7fdbf6ccee9278b9fa0ea29582/index.js:273758:9)
        at async ElasticsearchDateSlicer.initialize (/app/assets/71da69e118c73b7fdbf6ccee9278b9fa0ea29582/index.js:352442:25)
        at async /app/source/packages/job-components/dist/src/execution-context/base.js:62:17
        at async /app/source/node_modules/p-map/index.js:57:22
[2024-06-03T15:43:03.945Z] DEBUG: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: execution shutdown was called for ex de64394f-b32d-4680-90a0-5b7ae6e7b386 (assignment=execution_controller, module=execution_controller, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
[2024-06-03T15:43:03.947Z]  INFO: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: shutting down (assignment=execution_controller, module=state_storage, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
[2024-06-03T15:43:03.947Z]  INFO: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: shutting down. (assignment=execution_controller, module=ex_storage, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
[2024-06-03T15:43:03.954Z]  INFO: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: client de64394f-b32d-4680-90a0-5b7ae6e7b386 disconnected { reason: 'io client disconnect' } (assignment=execution_controller, module=messaging:client, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
[2024-06-03T15:43:08.951Z]  INFO: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: client 10.244.0.15__0KKV0XR1 disconnected { reason: undefined } (assignment=execution_controller, module=messaging:server, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
[2024-06-03T15:43:08.952Z]  INFO: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: client 10.244.0.14__J5Br9Zg3 disconnected { reason: undefined } (assignment=execution_controller, module=messaging:server, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
[2024-06-03T15:43:08.954Z]  WARN: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: execution controller de64394f-b32d-4680-90a0-5b7ae6e7b386 is shutdown (assignment=execution_controller, module=execution_controller, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
[2024-06-03T15:43:08.955Z]  INFO: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: execution_controller shutdown, already shutting down, remaining 25s (assignment=execution_controller, module=execution_controller:shutdown_handler, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
[2024-06-03T15:43:09.956Z] DEBUG: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: flushed logs successfully, will exit with code 0 (assignment=execution_controller, module=execution_controller:shutdown_handler, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
[2024-06-03T15:43:09.957Z]  INFO: teraslice/10 on ts-exc-failing-job-e2566fb1-963b-2z7bb: execution_controller shutdown took 6s, exit with zero status code (assignment=execution_controller, module=execution_controller:shutdown_handler, worker_id=IqvPk_Wf, ex_id=de64394f-b32d-4680-90a0-5b7ae6e7b386, job_id=e2566fb1-963b-45a8-801e-07aeec18736d)
```

Also because the execution controller is in a `completed` state instead of `failed` in terms of kubernetes, the worker pods idle and never shutdown

**Comment by sotojn** [comment]
Will be posting my broken slicer results soon, which force shutdown in the slicer code. Which hopefully won't allow for the ex to update the job to `failed`, causing original issue.

**Comment by busma13** [comment]
I created a slicer that adds random bytes to an array until the execution controller pod OOMs.
Results:

The job status if left in `running`:
Command:  `earl ex list localhost`
```
 name                    lifecycle   slicers  workers  _status  ex_id                                 job_id                                _created                  _updated
 make ex controller oom  persistent  1        1        running  abdc5e69-9b95-4fbb-8bbe-f964e9530013  585967f4-8a21-4282-81c6-e3a95ec4ca37  2024-06-04T14:30:49.572Z  2024-06-04T14:30:55.019Z
```

The only teraslice resources remaining are related to the master:
Command: `kubectl get -n ts-dev1 all`
```
NAME                                    READY   STATUS    RESTARTS   AGE
pod/teraslice-master-67f49bfd75-h6lkf   1/1     Running   0          16h

NAME                       TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/teraslice-master   NodePort   10.96.223.154   <none>        5678:30678/TCP   16h

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/teraslice-master   1/1     1            1           16h

NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/teraslice-master-67f49bfd75   1         1         1       16h
```

The last logs of the worker:
```
[2024-06-04T14:31:53.684Z] DEBUG: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: 10.244.0.24__lfubfxZ8 worker is idle (assignment=worker, module=worker, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:53.790Z] DEBUG: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: 10.244.0.24__lfubfxZ8 worker is idle (assignment=worker, module=worker, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:53.891Z] DEBUG: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: 10.244.0.24__lfubfxZ8 worker is idle (assignment=worker, module=worker, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:53.907Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: worker received process:SIGTERM, exiting in 30s... (assignment=worker, module=worker:shutdown_handler, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:53.996Z] DEBUG: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: 10.244.0.24__lfubfxZ8 worker is idle (assignment=worker, module=worker, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.007Z]  WARN: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: worker shutdown was called for execution abdc5e69-9b95-4fbb-8bbe-f964e9530013 due to event: SIGTERM (assignment=worker, module=worker, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.007Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: flushing slice b6e45b3e-a440-4083-a8a5-9b5ea375ceba (assignment=worker, module=worker_context, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.011Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: analytics for slice: slice_id: "b6e45b3e-a440-4083-a8a5-9b5ea375ceba", slicer_id: 0, slicer_order: 755, _created: "2024-06-04T14:31:38.141Z", time: [0, 0], memory: [10360, 2528], size: [10, 10] (assignment=worker, module=slice, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37, slice_id=b6e45b3e-a440-4083-a8a5-9b5ea375ceba)
[2024-06-04T14:31:54.012Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: [START] "job-observer" operation shutdown (assignment=worker, module=worker_context, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.012Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: [START] "oom_slicer" operation shutdown (assignment=worker, module=worker_context, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.012Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: [START] "noop" operation shutdown (assignment=worker, module=worker_context, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.012Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: [FINISH] "job-observer" operation shutdown, took 0ms (assignment=worker, module=worker_context, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.012Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: [FINISH] "oom_slicer" operation shutdown, took 0ms (assignment=worker, module=worker_context, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.012Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: [FINISH] "noop" operation shutdown, took 0ms (assignment=worker, module=worker_context, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.012Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: shutting down (assignment=worker, module=state_storage, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.012Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: shutting down. (assignment=worker, module=analytics_storage, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.014Z] DEBUG: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: flushed 2, on shutdown records to index ts-dev1__analytics* (assignment=worker, module=analytics_storage, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.014Z]  WARN: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: worker 10.244.0.24__lfubfxZ8 is shutdown for execution abdc5e69-9b95-4fbb-8bbe-f964e9530013, processed 755 slices (assignment=worker, module=worker, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.014Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: worker shutdown, already shutting down, remaining 30s (assignment=worker, module=worker:shutdown_handler, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:54.097Z] DEBUG: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: 10.244.0.24__lfubfxZ8 worker is idle (assignment=worker, module=worker, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:55.015Z] DEBUG: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: flushed logs successfully, will exit with code 0 (assignment=worker, module=worker:shutdown_handler, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:55.015Z]  INFO: teraslice/10 on ts-wkr-make-ex-controller-oom-585967f4-8a21-d9fc6b65c-vv82b: worker shutdown took 1s, exit with 0 status code (assignment=worker, module=worker:shutdown_handler, worker_id=lfubfxZ8, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
```

The last logs for the execution controller:
```
[2024-06-04T14:31:38.043Z] DEBUG: teraslice/10 on ts-exc-make-ex-controller-oom-585967f4-8a21-2vtd2: dispatched slice 976d70e0-36fa-4a4b-bb47-a22e7ff3b35b to worker 10.244.0.24__lfubfxZ8 (assignment=execution_controller, module=execution_controller, worker_id=x7gwq2L5, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:38.051Z]  INFO: teraslice/10 on ts-exc-make-ex-controller-oom-585967f4-8a21-2vtd2: worker 10.244.0.24__lfubfxZ8 has completed its slice 976d70e0-36fa-4a4b-bb47-a22e7ff3b35b (assignment=execution_controller, module=execution_controller, worker_id=x7gwq2L5, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
@@@@@@@@ OOMSlicer, buffer mb:  377.5
[2024-06-04T14:31:38.105Z] DEBUG: teraslice/10 on ts-exc-make-ex-controller-oom-585967f4-8a21-2vtd2: dispatched slice d0d82ed8-7d76-48b0-bfa8-0242a1a6c163 to worker 10.244.0.24__lfubfxZ8 (assignment=execution_controller, module=execution_controller, worker_id=x7gwq2L5, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:38.118Z]  INFO: teraslice/10 on ts-exc-make-ex-controller-oom-585967f4-8a21-2vtd2: worker 10.244.0.24__lfubfxZ8 has completed its slice d0d82ed8-7d76-48b0-bfa8-0242a1a6c163 (assignment=execution_controller, module=execution_controller, worker_id=x7gwq2L5, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
@@@@@@@@ OOMSlicer, buffer mb:  378
[2024-06-04T14:31:38.149Z] DEBUG: teraslice/10 on ts-exc-make-ex-controller-oom-585967f4-8a21-2vtd2: dispatched slice b6e45b3e-a440-4083-a8a5-9b5ea375ceba to worker 10.244.0.24__lfubfxZ8 (assignment=execution_controller, module=execution_controller, worker_id=x7gwq2L5, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
[2024-06-04T14:31:38.159Z]  INFO: teraslice/10 on ts-exc-make-ex-controller-oom-585967f4-8a21-2vtd2: worker 10.244.0.24__lfubfxZ8 has completed its slice b6e45b3e-a440-4083-a8a5-9b5ea375ceba (assignment=execution_controller, module=execution_controller, worker_id=x7gwq2L5, ex_id=abdc5e69-9b95-4fbb-8bbe-f964e9530013, job_id=585967f4-8a21-4282-81c6-e3a95ec4ca37)
```

The master logs:
```
[2024-06-04T14:30:55.001Z]  INFO: teraslice/21 on teraslice-master-67f49bfd75-h6lkf: execution abdc5e69-9b95-4fbb-8bbe-f964e9530013 is connected (assignment=cluster_master, module=kubernetes_cluster_service, worker_id=4mv-kd0l)
[2024-06-04T14:31:38.219Z]  INFO: teraslice/21 on teraslice-master-67f49bfd75-h6lkf: client abdc5e69-9b95-4fbb-8bbe-f964e9530013 disconnected { reason: 'transport close' } (assignment=cluster_master, module=messaging:server, worker_id=4mv-kd0l)
[2024-06-04T14:31:53.068Z]  INFO: teraslice/21 on teraslice-master-67f49bfd75-h6lkf: client abdc5e69-9b95-4fbb-8bbe-f964e9530013 reconnected (assignment=cluster_master, module=messaging:server, worker_id=4mv-kd0l)
[2024-06-04T14:31:53.878Z] ERROR: teraslice/21 on teraslice-master-67f49bfd75-h6lkf: terminal error for execution: abdc5e69-9b95-4fbb-8bbe-f964e9530013, shutting down execution, caused by Execution abdc5e69-9b95-4fbb-8bbe-f964e9530013 was starting in running status sending execution:finished event to cluster master (assignment=cluster_master, module=execution_service, worker_id=4mv-kd0l, err.code=INTERNAL_SERVER_ERROR)
    TSError: terminal error for execution: abdc5e69-9b95-4fbb-8bbe-f964e9530013, shutting down execution, caused by Execution abdc5e69-9b95-4fbb-8bbe-f964e9530013 was starting in running status sending execution:finished event to cluster master
        at ExecutionService._finishExecution (file:///app/source/packages/teraslice/dist/src/lib/cluster/services/execution.js:167:27)
        at Server.<anonymous> (/app/source/packages/teraslice-messaging/dist/src/cluster-master/server.js:77:13)
        at Server.emit (node:events:517:28)
        at Server.emit (/app/source/packages/teraslice-messaging/dist/src/messenger/core.js:108:15)
        at /app/source/packages/teraslice-messaging/dist/src/cluster-master/server.js:82:18
        at Socket.<anonymous> (/app/source/packages/teraslice-messaging/dist/src/messenger/core.js:59:39)
        at Socket.emit (node:events:517:28)
        at /app/source/node_modules/socket.io/lib/socket.js:503:12
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[2024-06-04T14:31:53.880Z] DEBUG: teraslice/21 on teraslice-master-67f49bfd75-h6lkf: execution abdc5e69-9b95-4fbb-8bbe-f964e9530013 finished, shutting down execution (assignment=cluster_master, module=execution_service, worker_id=4mv-kd0l)
[2024-06-04T14:31:53.882Z]  INFO: teraslice/21 on teraslice-master-67f49bfd75-h6lkf: client abdc5e69-9b95-4fbb-8bbe-f964e9530013 disconnected { reason: 'client namespace disconnect' } (assignment=cluster_master, module=messaging:server, worker_id=4mv-kd0l)
[2024-06-04T14:31:53.886Z]  INFO: teraslice/21 on teraslice-master-67f49bfd75-h6lkf: k8s._deleteObjByExId: abdc5e69-9b95-4fbb-8bbe-f964e9530013 execution_controller jobs deleting: ts-exc-make-ex-controller-oom-585967f4-8a21 (assignment=cluster_master, module=kubernetes_cluster_service, worker_id=4mv-kd0l)
[2024-06-04T14:34:23.750Z] ERROR: teraslice/21 on teraslice-master-67f49bfd75-h6lkf: Timed out after 2m, waiting for message "execution:analytics" (assignment=cluster_master, module=api_service, worker_id=4mv-kd0l)
    Error: Timed out after 2m, waiting for message "execution:analytics"
        at Server.handleSendResponse (/app/source/packages/teraslice-messaging/dist/src/messenger/core.js:43:19)
        at async Promise.all (index 0)
        at async ExecutionService.getControllerStats (file:///app/source/packages/teraslice/dist/src/lib/cluster/services/execution.js:277:25)
        at async file:///app/source/packages/teraslice/dist/src/lib/cluster/services/api.js:477:31
        at async file:///app/source/packages/teraslice/dist/src/lib/utils/api_utils.js:37:28
```

**Comment by godber** [comment]
We have tried to fix this and we believe we have, so I will close this for now.  We can re-open if necessary.
