### ISSUE TITLE
Disruption in the target ES cluster causes the job to hang

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#269]
If something happens to cause serious issues in the ES cluster any running jobs appear to simply get stuck. They can be stopped but do not fail automatically. It will be tricky to handle this gracefully as we do want to allow for temporary disruptions.

**Comment by kstaken** [comment]
We're seeing this periodically in the test suite on the 'should reindex data 10 times' test. It doesn't occur on every run of the test but is fairly common. When it happens the test suite throws the stack below and the job doesn't exit so it leaks the workers for the worker and slicer. We're clearly not handling this 'socket hang up' error correctly. Hopefully we can figure out a way to consistently reproduce that error.

```
Unhandled rejection RequestError: Error: socket hang up
    at new RequestError (/Users/kstaken/projects/opensource/teraslice-client-js/node_modules/request-promise/lib/errors.js:14:15)
    at Request.RP$callback [as _callback] (/Users/kstaken/projects/opensource/teraslice-client-js/node_modules/request-promise/lib/rp.js:60:25)
    at self.callback (/Users/kstaken/projects/opensource/teraslice-client-js/node_modules/request-promise/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/kstaken/projects/opensource/teraslice-client-js/node_modules/request-promise/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnEnd (_http_client.js:305:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by kstaken** [comment]
I haven't seen this issue in a while so it's likely been addressed through other robustness related changes. Closing.
