### ISSUE TITLE
Upgrade Teraslice to node 16 docker image

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3270]
We need to upgrade Teraslice to the node 16 docker image.  If node 18 works, that's fine too.  But I think this is complicated by the asset build process.  The assets need to build for appropriate target node versions.

**Comment by godber** [comment]
I finally got this to build 

https://app.travis-ci.com/github/terascope/base-docker-image/builds/260894118

We now have a node `v16.19.1-core` image:

https://hub.docker.com/layers/terascope/node-base/16.19.1-core/images/sha256-d9f26668e2ce785330ec9c071ffa3ee660d73ff67701d699bf79f2831ebc0a89?context=explore

I've gotten rid of the non-core images on the assumption that the teraslice images no longer need the kafka connector built into them.

**Comment by godber** [comment]
The e2e test fails with a kafka error:

https://app.travis-ci.com/github/terascope/teraslice/jobs/596587644#L2645

```
{"name":"teraslice","assignment":"worker","hostname":"6515946ff32f","pid":369,"level":50,"err":{"message":"Could not find connector implementation for: kafka\n","name":"Error","stack":"Error: Could not find connector implementation for: kafka\n\n    at createConnection (/app/source/packages/terafoundation/dist/src/connector-utils.js:102:15)\n    at Object.getConnection (/app/source/packages/terafoundation/dist/src/api/index.js:88:75)\n    at KafkaReaderApi.create (/app/assets/****************************************/index.js:56506:49)\n    at Object.create (/app/assets/****************************************/index.js:51324:51)\n    at KafkaFetcher.initialize (/app/assets/****************************************/index.js:56292:32)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /app/source/packages/job-components/dist/src/execution-context/base.js:61:17\n    at async /app/source/node_modules/p-map/index.js:57:22"},"msg":"Teraslice Worker shutting down due to failure!","time":"2023-02-22T23:06:49.473Z","v":0}
```

stack trace:

```
Error: Could not find connector implementation for: kafka

    at createConnection (/app/source/packages/terafoundation/dist/src/connector-utils.js:102:15)
    at Object.getConnection (/app/source/packages/terafoundation/dist/src/api/index.js:88:75)
    at KafkaReaderApi.create (/app/assets/****************************************/index.js:56506:49)
    at Object.create (/app/assets/****************************************/index.js:51324:51)
    at KafkaFetcher.initialize (/app/assets/****************************************/index.js:56292:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/source/packages/job-components/dist/src/execution-context/base.js:61:17
    at async /app/source/node_modules/p-map/index.js:57:22"
```

**Comment by jsnoble** [comment]
we are looking to jump straight to node v18 now
