### ISSUE TITLE
Teraslice master in broken state if it comes up before ES state cluster

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3280]
When updating my dev setup for Teraslice in minikube I encountered a problem with Teraslice when the Teraslice master comes up before the elasticsearch state cluster.  You can see the calls to `create_client` fail, then you can see it goes into a loop of errors: `Cannot read property 'index_exists' of undefined`

```
kubectl -n ts-dev1 logs teraslice-master-7956d49b7c-z6c8c | bunyan
[2022-08-18T19:52:27.134Z]  INFO: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: Service starting (assignment=node_master)
[2022-08-18T19:52:27.139Z] DEBUG: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: messaging service configuration for assignment node_master (assignment=node_master, module=node_master)
[2022-08-18T19:52:27.140Z]  INFO: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: node teraslice-master-7956d49b7c-z6c8c is attempting to connect to cluster_master: http://127.0.0.1:5678 (assignment=node_master, module=node_master)
[2022-08-18T19:52:27.193Z] DEBUG: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: client network connection is online (assignment=node_master, module=node_master)
[2022-08-18T19:52:27.193Z] DEBUG: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: node teraslice-master-7956d49b7c-z6c8c is creating the cluster_master (assignment=node_master, module=node_master)
[2022-08-18T19:52:27.194Z]  INFO: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: Starting 1 cluster_master (assignment=node_master)
[2022-08-18T19:52:27.204Z] DEBUG: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: node teraslice-master-7956d49b7c-z6c8c is creating assets endpoint on port 45679 (assignment=node_master, module=node_master)
[2022-08-18T19:52:27.204Z]  INFO: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: Starting 1 assets_service (assignment=node_master)
[2022-08-18T19:52:27.283Z] DEBUG: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: worker process has come online (assignment=node_master, module=node_master)
[2022-08-18T19:52:27.306Z] DEBUG: teraslice/8 on teraslice-master-7956d49b7c-z6c8c: worker process has come online (assignment=node_master, module=node_master)
[2022-08-18T19:52:29.552Z]  INFO: teraslice/21 on teraslice-master-7956d49b7c-z6c8c: creating connection for elasticsearch-next (assignment=assets_service)
[2022-08-18T19:52:29.738Z] ERROR: teraslice/21 on teraslice-master-7956d49b7c-z6c8c: Failed attempt connecting to elasticsearch: {"connection":"default","index":"ts-dev1__assets"} (will retry) (assignment=assets_service, module=elasticsearch_backend, worker_id=MkDieUNu, storageName=assets, err.code=INTERNAL_SERVER_ERROR)
    TSError: Failure initializing asset index: ts-dev1__assets, caused by Error: Could not create a client for config {
        "node": [
            "http://elasticsearch.ts-dev1.svc.cluster.local:9200"
        ],
        "sniffOnStart": false,
        "sniffOnConnectionFault": false,
        "requestTimeout": 120000,
        "maxRetries": 3
    }
        at /app/source/packages/teraslice/lib/storage/backends/elasticsearch_store.js:562:31
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
    Caused by: Error: Could not create a client for config {
        "node": [
            "http://elasticsearch.ts-dev1.svc.cluster.local:9200"
        ],
        "sniffOnStart": false,
        "sniffOnConnectionFault": false,
        "requestTimeout": 120000,
        "maxRetries": 3
    }
        at createClient (/app/source/packages/elasticsearch-store/dist/src/elasticsearch-client/create-client.js:139:15)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Object.createClient (/app/source/packages/terafoundation/dist/src/api/index.js:60:36)
        at async getClientAsync (/app/source/packages/job-components/dist/src/register-apis.js:85:24)
[2022-08-18T19:52:29.892Z]  INFO: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: cluster master listening on port 5678 (assignment=cluster_master, module=cluster_master, worker_id=bomwDEBF)
[2022-08-18T19:52:29.898Z]  INFO: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: creating connection for elasticsearch-next (assignment=cluster_master)
[2022-08-18T19:52:29.927Z]  INFO: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: creating connection for elasticsearch-next (assignment=cluster_master)
[2022-08-18T19:52:29.929Z]  INFO: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: creating connection for elasticsearch-next (assignment=cluster_master)
[2022-08-18T19:52:30.143Z] ERROR: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: Failed attempt connecting to elasticsearch: {"connection":"default","index":"ts-dev1__state*"} (will retry) (assignment=cluster_master, module=elasticsearch_backend, worker_id=bomwDEBF, storageName=state, err.code=INTERNAL_SERVER_ERROR)
    TSError: Failure initializing state index: ts-dev1__state*, caused by Error: Could not create a client for config {
        "node": [
            "http://elasticsearch.ts-dev1.svc.cluster.local:9200"
        ],
        "sniffOnStart": false,
        "sniffOnConnectionFault": false,
        "requestTimeout": 120000,
        "maxRetries": 3
    }
        at /app/source/packages/teraslice/lib/storage/backends/elasticsearch_store.js:562:31
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
    Caused by: Error: Could not create a client for config {
        "node": [
            "http://elasticsearch.ts-dev1.svc.cluster.local:9200"
        ],
        "sniffOnStart": false,
        "sniffOnConnectionFault": false,
        "requestTimeout": 120000,
        "maxRetries": 3
    }
        at createClient (/app/source/packages/elasticsearch-store/dist/src/elasticsearch-client/create-client.js:139:15)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Object.createClient (/app/source/packages/terafoundation/dist/src/api/index.js:60:36)
        at async getClientAsync (/app/source/packages/job-components/dist/src/register-apis.js:85:24)
[2022-08-18T19:52:30.145Z] ERROR: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: Failed attempt connecting to elasticsearch: {"connection":"default","index":"ts-dev1__jobs"} (will retry) (assignment=cluster_master, module=elasticsearch_backend, worker_id=bomwDEBF, storageName=jobs, err.code=INTERNAL_SERVER_ERROR)
    TSError: Failure initializing job index: ts-dev1__jobs, caused by Error: Could not create a client for config {
        "node": [
            "http://elasticsearch.ts-dev1.svc.cluster.local:9200"
        ],
        "sniffOnStart": false,
        "sniffOnConnectionFault": false,
        "requestTimeout": 120000,
        "maxRetries": 3
    }
        at /app/source/packages/teraslice/lib/storage/backends/elasticsearch_store.js:562:31
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
    Caused by: Error: Could not create a client for config {
        "node": [
            "http://elasticsearch.ts-dev1.svc.cluster.local:9200"
        ],
        "sniffOnStart": false,
        "sniffOnConnectionFault": false,
        "requestTimeout": 120000,
        "maxRetries": 3
    }
        at createClient (/app/source/packages/elasticsearch-store/dist/src/elasticsearch-client/create-client.js:139:15)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Object.createClient (/app/source/packages/terafoundation/dist/src/api/index.js:60:36)
        at async getClientAsync (/app/source/packages/job-components/dist/src/register-apis.js:85:24)
[2022-08-18T19:52:30.146Z] ERROR: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: Failed attempt connecting to elasticsearch: {"connection":"default","index":"ts-dev1__ex"} (will retry) (assignment=cluster_master, module=elasticsearch_backend, worker_id=bomwDEBF, storageName=execution, err.code=INTERNAL_SERVER_ERROR)
    TSError: Failure initializing ex index: ts-dev1__ex, caused by Error: Could not create a client for config {
        "node": [
            "http://elasticsearch.ts-dev1.svc.cluster.local:9200"
        ],
        "sniffOnStart": false,
        "sniffOnConnectionFault": false,
        "requestTimeout": 120000,
        "maxRetries": 3
    }
        at /app/source/packages/teraslice/lib/storage/backends/elasticsearch_store.js:562:31
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
    Caused by: Error: Could not create a client for config {
        "node": [
            "http://elasticsearch.ts-dev1.svc.cluster.local:9200"
        ],
        "sniffOnStart": false,
        "sniffOnConnectionFault": false,
        "requestTimeout": 120000,
        "maxRetries": 3
    }
        at createClient (/app/source/packages/elasticsearch-store/dist/src/elasticsearch-client/create-client.js:139:15)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Object.createClient (/app/source/packages/terafoundation/dist/src/api/index.js:60:36)
        at async getClientAsync (/app/source/packages/job-components/dist/src/register-apis.js:85:24)
[2022-08-18T19:52:32.997Z]  INFO: teraslice/21 on teraslice-master-7956d49b7c-z6c8c: Attempting to connect to elasticsearch: {"connection":"default","index":"ts-dev1__assets"}, caused by TypeError: Cannot read property 'index_exists' of undefined (assignment=assets_service, module=elasticsearch_backend, worker_id=MkDieUNu, storageName=assets)
[2022-08-18T19:52:33.326Z]  INFO: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: Attempting to connect to elasticsearch: {"connection":"default","index":"ts-dev1__jobs"}, caused by TypeError: Cannot read property 'index_exists' of undefined (assignment=cluster_master, module=elasticsearch_backend, worker_id=bomwDEBF, storageName=jobs)
[2022-08-18T19:52:33.388Z]  INFO: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: Attempting to connect to elasticsearch: {"connection":"default","index":"ts-dev1__ex"}, caused by TypeError: Cannot read property 'index_exists' of undefined (assignment=cluster_master, module=elasticsearch_backend, worker_id=bomwDEBF, storageName=execution)
[2022-08-18T19:52:33.532Z]  INFO: teraslice/15 on teraslice-master-7956d49b7c-z6c8c: Attempting to connect to elasticsearch: {"connection":"default","index":"ts-dev1__state*"}, caused by TypeError: Cannot read property 'index_exists' of undefined (assignment=cluster_master, module=elasticsearch_backend, worker_id=bomwDEBF, storageName=state)
...
```

**Comment by godber** [comment]
Restarting the teraslice-master pod makes this work just fine.
