### ISSUE TITLE
Fix asset.json file not found error in e2e tests

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3452]
This error pops up every so often when running end to end tests. I'm not sure if this is related to our recent changes to the e2e testing framework. 

```
*  pending   Generating example data...
ℹ  info      Generating ts_test_example-100 example data
ℹ  info      Generating ts_test_example-1000 example data
✖  error     Failure to generate example data ts_test_example-100 Error: Failure to get assets, caused by Error: ENOENT: no such file or directory, utime '/app/assets/2c077dba634ce7ad5a15e46209aba090c667f791/asset.json'
    at makeErrorFromResponse (/home/runner/work/teraslice/teraslice/packages/teraslice-client-js/dist/src/client.js:134:19)
    at Executions._makeRequest (/home/runner/work/teraslice/teraslice/packages/teraslice-client-js/dist/src/client.js:79:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Executions.submit (/home/runner/work/teraslice/teraslice/packages/teraslice-client-js/dist/src/executions.js:24:21)
    at async TerasliceHarness.generate (/home/runner/work/teraslice/teraslice/e2e/test/teraslice-harness.js:483:28)
    at async Promise.all (index 0)
    at async TerasliceHarness.generateTestData (/home/runner/work/teraslice/teraslice/e2e/test/teraslice-harness.js:507:13)
    at async module.exports (/home/runner/work/teraslice/teraslice/e2e/test/global.setup.js:55:9)
    at async /home/runner/work/teraslice/teraslice/node_modules/@jest/core/build/runGlobalHook.js:109:13 {
  error: 500,
  code: 500,
  statusCode: 500
}
✖  error     Data generation failed took 4s
✖  error     Setup failed, `docker-compose logs` may provide clues
✖  error     Error: Failure to get assets, caused by Error: ENOENT: no such file or directory, utime '/app/assets/2c077dba634ce7ad5a15e46209aba090c667f791/asset.json' 
    at makeErrorFromResponse (/home/runner/work/teraslice/teraslice/packages/teraslice-client-js/dist/src/client.js:134:19)
    at Executions._makeRequest (/home/runner/work/teraslice/teraslice/packages/teraslice-client-js/dist/src/client.js:79:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Executions.submit (/home/runner/work/teraslice/teraslice/packages/teraslice-client-js/dist/src/executions.js:24:21)
    at async TerasliceHarness.generate (/home/runner/work/teraslice/teraslice/e2e/test/teraslice-harness.js:483:28)
    at async Promise.all (index 0)
    at async TerasliceHarness.generateTestData (/home/runner/work/teraslice/teraslice/e2e/test/teraslice-harness.js:507:13)
    at async module.exports (/home/runner/work/teraslice/teraslice/e2e/test/global.setup.js:55:9)
    at async /home/runner/work/teraslice/teraslice/node_modules/@jest/core/build/runGlobalHook.js:109:13
◼  test suite "e2e" Timer run for: 85.14s
$ ./scripts/logs.sh -n 2000
⬤  debug     Running test/global.teardown.js
✖  error     TSError: Failed to teardown test for "e2e", caused by Error: Could not create a client with config {"node":"http://10.1.54.1:49200"} 
    at globalTeardown (/home/runner/work/teraslice/teraslice/packages/scripts/dist/src/helpers/test-runner/utils.js:269:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/runner/work/teraslice/teraslice/packages/scripts/dist/src/helpers/test-runner/index.js:246:13
    at async TestTracker.runCleanupByKey (/home/runner/work/teraslice/teraslice/packages/scripts/dist/src/helpers/test-runner/tracker.js:52:13)
    at async TestTracker.end (/home/runner/work/teraslice/teraslice/packages/scripts/dist/src/helpers/test-runner/tracker.js:84:17)
    at async TestTracker.finish (/home/runner/work/teraslice/teraslice/packages/scripts/dist/src/helpers/test-runner/tracker.js:75:9)

✖  fatal     Command failed with exit code 1: jest --forceExit --coverage false --color --silent --verbose false --runInBand --bail
```

**Comment by busma13** [comment]
This error must be related to the first:
```
*  pending   Generating example data...
ℹ  info      Generating ts_test_example-100 example data
ℹ  info      Generating ts_test_example-1000 example data
✖  error     Failure to generate example data ts_test_example-1000 Error: Failure to get assets, caused by Error: EEXIST: file already exists, mkdir '/app/assets/a0fa547cf8bf9b33bd5f44176c43089b490b3f5e'
    at makeErrorFromResponse (/home/runner/work/teraslice/teraslice/packages/teraslice-client-js/dist/src/client.js:134:19)
    at Executions._makeRequest (/home/runner/work/teraslice/teraslice/packages/teraslice-client-js/dist/src/client.js:79:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Executions.submit (/home/runner/work/teraslice/teraslice/packages/teraslice-client-js/dist/src/executions.js:24:21)
    at async TerasliceHarness.generate (/home/runner/work/teraslice/teraslice/e2e/test/teraslice-harness.js:484:28)
    at async Promise.all (index 1)
    at async TerasliceHarness.generateTestData (/home/runner/work/teraslice/teraslice/e2e/test/teraslice-harness.js:508:13)
    at async module.exports (/home/runner/work/teraslice/teraslice/e2e/test/global.setup.js:55:9)
    at async /home/runner/work/teraslice/teraslice/node_modules/@jest/core/build/runGlobalHook.js:109:13 {
  error: 500,
  code: 500,
  statusCode: 500
}
```

**Comment by godber** [comment]
Perhaps this is the asset not being unzipped yet on this line:

https://github.com/terascope/teraslice/blob/bfe9737c15660b7a65eeecbd6f7ac3bcd52cab75/e2e/test/teraslice-harness.js#L472

Making it get a 500 error like this

```
✖  error     Failure to generate example data ts_test_example-100 Error: Failure to get assets, caused by Error: ENOENT: no such file or directory, utime '/app/assets/2c077dba634ce7ad5a15e46209aba090c667f791/asset.json'
...
{
  error: 500,
  code: 500,
  statusCode: 500
}
```

Maybe if it retried a little bit later to submit the job it would succeed.  Rather than waiting, just retry on `500` a few times (with a wait between each retry ... look up exponential backoff, maybe we have a util for this, look at `pRetry` and friends)

**Comment by godber** [comment]
We haven't seen this in quite a while.  Closing until it re-surfaces.
