### ISSUE TITLE
Fix documentation for Teraslice

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3489]
Merging the typescript PR broke our documentation CI.

I have temporarily disabled the CI in this PR:

https://github.com/terascope/teraslice/pull/3488

We should make the docs work ... preferably without snowballing into an upgrade of docusaurus.

**Comment by sotojn** [comment]
When I run `yarn docs` in the root of teraslice I am getting a type error. This only seems to occur when building docs for @terascope/utils. It correctly builds docs for every package before it. 

```
$ tsc --build

★  star      Building docs for @terascope/eslint-config

★  star      Building docs for @terascope/types
…  awaiting  building typedocs for package @terascope/types
Loaded plugin /Users/jsoto/Workspace/teraslice/node_modules/typedoc-plugin-markdown
warning You are running with an unsupported TypeScript version! If TypeDoc crashes, this is why. TypeDoc supports 4.6, 4.7, 4.8, 4.9, 5.0
Documentation generated at /Users/jsoto/Workspace/teraslice/docs/packages/types/api
✔  success   generated docs for package @terascope/types
$ tsc --build

★  star      Building docs for @terascope/utils
…  awaiting  building typedocs for package @terascope/utils
Loaded plugin /Users/jsoto/Workspace/teraslice/node_modules/typedoc-plugin-markdown
warning You are running with an unsupported TypeScript version! If TypeDoc crashes, this is why. TypeDoc supports 4.6, 4.7, 4.8, 4.9, 5.0
ts-scripts docs [packages..]

Update documentation for all packages or a specific package

Positionals:
  packages  Run scripts for one or more packages                                                                                 [array] [default: []]

Options:
  -h, --help     Show help                                                                                                                   [boolean]
  -v, --version  Show version number                                                                                                         [boolean]

TypeError: Cannot read properties of undefined (reading 'name')
    at /Users/jsoto/Workspace/teraslice/node_modules/typedoc/dist/lib/converter/types.js:559:100
    at Array.map (<anonymous>)
    at Object.convertType (/Users/jsoto/Workspace/teraslice/node_modules/typedoc/dist/lib/converter/types.js:559:34)
    at convertType (/Users/jsoto/Workspace/teraslice/node_modules/typedoc/dist/lib/converter/types.js:105:34)
    at /Users/jsoto/Workspace/teraslice/node_modules/typedoc/dist/lib/converter/types.js:427:53
    at Array.map (<anonymous>)
    at Object.convertType (/Users/jsoto/Workspace/teraslice/node_modules/typedoc/dist/lib/converter/types.js:427:40)
    at convertType (/Users/jsoto/Workspace/teraslice/node_modules/typedoc/dist/lib/converter/types.js:105:34)
    at Converter.convertType (/Users/jsoto/Workspace/teraslice/node_modules/typedoc/dist/lib/converter/converter.js:93:40)
    at createSignature (/Users/jsoto/Workspace/teraslice/node_modules/typedoc/dist/lib/converter/factories/signature.js:48:41)
error Command failed with exit code 1.
```

**Comment by godber** [comment]
@sotojn and I talked about this, he was going to try and upgrade to the new version of typedoc.

**Comment by busma13** [comment]
Ref: #3495

**Comment by godber** [comment]
I've merged this in and it fixed it, updated docs are now live:

![Screenshot 2023-12-12 at 12 57 26 PM](https://github.com/terascope/teraslice/assets/1249/f36ca8e6-5e09-44b3-b027-8257cf85db9c)
