### ISSUE TITLE
Moderator blocks job submission - crashed?

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#377]
This may be related to #376. The next job I tried to submit came back with this failure so it appears the moderator may have crashed. This left the job in pending status.

```
{
    "error": 500,
    "message": "Job submission failed: Error communicating with node: moderator:elasticsearch, Could not send msg: cluster:moderator:connection_ok, data: {\"data\":[\"es_d3\",\"es_util1\"],\"_msgID\":\"BJ0VNd_9x\"}"
}
```

**Comment by kstaken** [comment]
This is the only thing I could find in the logs.

```
"name":"teraslice","hostname":"hostname.internal","pid":654,"level":50,"msg":"Error: [object Object]\n    at Object.ensureErrorObject (/app/source/node_modules/bluebird/js/main/util.js:261:20)\n    at Promise._rejectCallback (/app/source/node_modules/bluebird/js/main/promise.js:472:22)\n    at Function.Promise.reject.Promise.rejected (/app/source/node_modules/bluebird/js/main/promise.js:199:9)\n    at /app/source/lib/cluster/moderator/modules/elasticsearch.js:177:44\n    at /app/source/node_modules/lodash/lodash.js:4944:15\n    at baseForOwn (/app/source/node_modules/lodash/lodash.js:3001:24)\n    at Function.forOwn (/app/source/node_modules/lodash/lodash.js:13002:24)\n    at /app/source/lib/cluster/moderator/modules/elasticsearch.js:133:23\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/app/source/node_modules/terafoundation/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/source/node_modules/terafoundation/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/app/source/node_modules/terafoundation/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/app/source/node_modules/terafoundation/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/app/source/node_modules/terafoundation/node_modules/bluebird/js/release/promise.js:691:18)\n    at Async._drainQueue (/app/source/node_modules/terafoundation/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/app/source/node_modules/terafoundation/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/terafoundation/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)","time":"2017-03-01T16:06:09.182Z","v":0}
```
