### ISSUE TITLE
[teraslice-cli] jobs-spec test fails reading file that was just created.

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3844]
https://github.com/terascope/teraslice/actions/runs/11620752664/job/32363197551?pr=3813

Summary of all failing tests
 FAIL  packages/teraslice-cli/test/helpers/jobs-spec.ts (9.849 s)
  ● Job helper class › export › should export all jobs to a custom directory

    /home/runner/work/teraslice/teraslice/packages/teraslice-cli/test/fixtures/job_exports/custom2/test-job-2.json: ENOENT: no such file or directory, open '/home/runner/work/teraslice/teraslice/packages/teraslice-cli/test/fixtures/job_exports/custom2/test-job-2.json'

      1110 |             jobFiles.push(fs.readJsonSync(path.join(customDir, 'test-job.json')));
      1111 |             jobFiles.push(fs.readJsonSync(path.join(customDir, 'test-job-1.json')));
    > 1112 |             jobFiles.push(fs.readJsonSync(path.join(customDir, 'test-job-2.json')));
           |                              ^
      1113 |
      1114 |             expect(jobFiles).toEqual(expect.arrayContaining([
      1115 |                 expect.objectContaining(

      at Object.readFileSync (node_modules/jsonfile/index.js:50:22)
      at Object.readJsonSync (packages/teraslice-cli/test/helpers/jobs-spec.ts:1112:30)

**Comment by busma13** [comment]
I think this has something to do with how jobs with the same name are saved in job.export().

```
await job.export();

// Since all 3 jobs have the same file name, and exportOne() is called concurrently on
// each job, 2 of the jobs may have to call createUniqueFilePath() a second or
// third time. This race condition means there is no order to the file names.
```

**Comment by busma13** [comment]
In #3887 this was solved by setting concurreny to 1, so only one job is exported at a time.
#3936 cleans up that fix to remove the pMap entirely.
