### ISSUE TITLE
port in use errors in CI

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3848]
We keep getting port in use errors.
I would like to try using `ss` to list all ports in `TIME_WAIT` to see if they are not being shut down fast enough.

The other option is to assign random ports.

Example failures:
https://github.com/terascope/teraslice/actions/runs/11981509936/job/33407933870

```
● Test suite failed to run

    listen EADDRINUSE: address already in use :::55678

      140 |             await new Promise((resolve, reject) => {
      141 |                 // @ts-expect-error
    > 142 |                 this.app.listen(this.port, (err: Error) => {
          |                          ^
      143 |                     if (err) {
      144 |                         reject(err);
      145 |                         return;

      at Function.apply [as listen] (node_modules/express/lib/application.js:635:24)
      at listen (packages/teraslice/src/lib/cluster/services/assets.ts:142:26)
      at AssetsService.initialize (packages/teraslice/src/lib/cluster/services/assets.ts:140:19)
      at Object.<anonymous> (packages/teraslice/test/services/assets-spec.ts:67:9)
```

https://github.com/terascope/teraslice/actions/runs/11941437795/job/33286764202
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint ts_test_kafka (fb60d1c2428b6a3ad031693a716c1897da234a8e33577b500cd45bd8242830ae): Error starting userland proxy: listen tcp4 0.0.0.0:49092: bind: address already in use.
```

**Comment by busma13** [comment]
I have found port related errors in 3 different spots:
- assets service
- teraslice messaging server
- docker run of service images

These 3 different areas may need to be handled separately.

**Comment by busma13** [comment]
The teraslice package has a `findPort()` function that some of the tests use. It returns a random open port. I am adding this to `assets-spec.ts`, which should resolve the first list item in my pervious comment.

**Comment by busma13** [comment]
https://github.com/terascope/teraslice/actions/runs/11921771709/job/33226709312

This failure uses the findPort() function. I am guessing multiple tests run this function at the same time and there end up being collisions. We use `porty` to test if the port is open, but it looks like we start at the same port for all these tests and move up until `porty` says one is open. Maybe 2 tests get assigned the same `open` port at the same time.

**Comment by busma13** [comment]
`findPort() allows you to set a port range, so I am giving each test a unique range to prevent collisions.

**Comment by godber** [comment]
Or has the added netstat command helped narrow trouble down.

**Comment by sotojn** [comment]
Got an address already in use error in my ci pipeline. There is somehow a time-wait on port `49206` at the time scripts tries to launch an opensearch docker container 

https://github.com/terascope/teraslice/actions/runs/12699065769/job/35398965430?pr=3887#step:8:40

**Comment by busma13** [comment]
> I have found port related errors in 3 different spots:
> 
>     * assets service tests
> 
>     * teraslice messaging server
> 
>     * `docker run` of service images
> 
> 
> These 3 different areas may need to be handled separately.

I am confident that the first 2 cases have been resolved. I am going to close this issue and make one specific to docker.

**Comment by busma13** [comment]
I've found another one: https://github.com/terascope/teraslice/actions/runs/14542656277/job/40803446341

```
{"name":"teraslice","assignment":"execution_controller","hostname":"e091fabe01ff","pid":197,"module":"messaging:server","worker_id":"ghK8ODWl","ex_id":"9df0ea26-401d-4ca4-bb0e-abe2c2bdf61d","job_id":"859db26e-0838-4a9b-a9fc-069bcb596f48","level":40,"err":{"message":"Port 46238 is already in-use","name":"TSError","stack":"TSError: Port 46238 is already in-use\n    at pRetry (file:///app/source/packages/utils/dist/src/promises.js:103:21)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Server.listen (file:///app/source/packages/teraslice-messaging/dist/src/messenger/server.js:80:9)\n    at async Server.start (file:///app/source/packages/teraslice-messaging/dist/src/execution-controller/server.js:41:9)\n    at async ExecutionController.initialize (file:///app/source/packages/teraslice/dist/src/lib/workers/execution-controller/index.js:169:9)\n    at async Service.initialize (file:///app/source/packages/teraslice/worker-service.js:40:9)\n    at async main (file:///app/source/packages/teraslice/worker-service.js:80:9)\n    at pRetry.retries (file:///app/source/packages/teraslice-messaging/dist/src/messenger/server.js:83:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async pRetry (file:///app/source/packages/utils/dist/src/promises.js:88:16)\n    at async Server.listen (file:///app/source/packages/teraslice-messaging/dist/src/messenger/server.js:80:9)\n    at async Server.start (file:///app/source/packages/teraslice-messaging/dist/src/execution-controller/server.js:41:9)\n    at async ExecutionController.initialize (file:///app/source/packages/teraslice/dist/src/lib/workers/execution-controller/index.js:169:9)\n    at async Service.initialize (file:///app/source/packages/teraslice/worker-service.js:40:9)\n    at async main (file:///app/source/packages/teraslice/worker-service.js:80:9)","code":"INTERNAL_SERVER_ERROR"},"msg":"retry error, retrying... {\n  retries: 3,\n  delay: 500,\n  maxDelay: 60000,\n  backoff: 2,\n  matches: [],\n  _currentDelay: 3293,\n  _context: null,\n  endWithFatal: true,\n  logError: [Function: logError]\n}","time":"2025-04-18T22:40:16.351Z","v":0}
```

check that failed:
```
        const testPort = async function (port: number) {
            return new Promise((resolve) => {
                const portTestServer = http.createServer();

                portTestServer.unref();

                portTestServer.once('error', () => {
                    portTestServer.close(() => {
                        return resolve(false);
                    });
                });

                portTestServer.once('listening', () => {
                    portTestServer.close(() => {
                        return resolve(true);
                    });
                });

                portTestServer.listen(port);
            });
        };
```
