### ISSUE TITLE
Modifying number of workers on active job doesn't appear to work

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#437]
When trying to change the number of runners in a currently running job I get a 405 error.  I am running it as follows:

```bash
curl localhost:5678/ex/b448f695-c19a-4a07-9bdf-00e47088b74f/_workers?total=10
{
    "error": 405,
    "message": "cannot GET endpoint /ex/b448f695-c19a-4a07-9bdf-00e47088b74f/_workers?total=10"
}
```

The job is actually running and is accessible at the `/ex/:ex_id/` endpoint:

```bash
curl localhost:5678/ex/b448f695-c19a-4a07-9bdf-00e47088b74f
{
    "name": "Test",
    "lifecycle": "persistent",
    "analytics": true,
    "max_retries": 3,
    "slicers": 1,
    "workers": 15,
    "operations": [
        ...
    ],
    "assets": null,
    "moderator": null,
    "job_id": "0d39a42d-aa3c-443d-8a86-4836f3739ebd",
    "_context": "ex",
    "_created": "2017-06-27T17:50:26.574Z",
    "_updated": "2017-06-27T18:10:38.990Z",
    "ex_id": "b448f695-c19a-4a07-9bdf-00e47088b74f",
    "_status": "failing",
    "_has_errors": "true"
}
```

**Comment by godber** [comment]
@kstaken you were asking about this yesterday, have you actually gotten it to work?

**Comment by godber** [comment]
Using `POST` yields a different error:

```
curl -XPOST localhost:5678/ex/${ex_id}/_workers?total=10
{
    "error": 404,
    "message": "TypeError: Cannot read property '_status' of undefined\n    at /app/source/node_modules/teraslice/lib/cluster/services/api.js:378:36\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:510:31)\n    at Promise._settlePromiseAt (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:584:18)\n    at Promise._settlePromises (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:700:14)\n    at Async._drainQueue (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)"
}
```

Here is the stack trace:

```
TypeError: Cannot read property '_status' of undefined
    at /app/source/node_modules/teraslice/lib/cluster/services/api.js:378:36
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```
