### ISSUE TITLE
getEventEmitter is not a function error on Teraslice startup

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#485]
When starting teraslice with the local config like
```
 node ./service.js -c examples/config/processor-master.yaml | bunyan
```

we receive the following error and teraslice is not listening on port 5678:

```
[2017-08-04T12:03:01.156Z] ERROR: teraslice/34431 on stretch.local: Error in worker: 13 pid: 34431
[2017-08-04T12:03:01.157Z] ERROR: teraslice/34431 on stretch.local: context.foundation.getEventEmitter is not a function
[2017-08-04T12:03:01.158Z] ERROR: teraslice/34431 on stretch.local:
    TypeError: context.foundation.getEventEmitter is not a function
        at Object.module.exports (/Users/godber/Workspace/terascope/opensource/teraslice/lib/cluster/cluster_master.js:11:37)
        at /Users/godber/Workspace/terascope/opensource/terafoundation/index.js:78:32
        at Function.forOwn (/Users/godber/Workspace/terascope/opensource/terafoundation/node_modules/lodash/dist/lodash.js:1907:15)
        at findWorkerCode (/Users/godber/Workspace/terascope/opensource/terafoundation/index.js:75:15)
        at Domain.<anonymous> (/Users/godber/Workspace/terascope/opensource/terafoundation/index.js:163:17)
        at Domain.run (domain.js:221:14)
        at module.exports (/Users/godber/Workspace/terascope/opensource/terafoundation/index.js:96:13)
        at Object.<anonymous> (/Users/godber/Workspace/terascope/opensource/teraslice/service.js:35:43)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.runMain (module.js:604:10)
        at run (bootstrap_node.js:389:7)
        at startup (bootstrap_node.js:149:9)
        at bootstrap_node.js:504:3
```

Reverting to the commit prior to the events commit (https://github.com/terascope/teraslice/pull/464) and the issue goes away:

```
 git checkout 596f200
```

**Comment by godber** [comment]
Not a bug, clearly the error is "`context.foundation.getEventEmitter` is not a function"

If you see the error reported above it means you need to update your terafoundation.
