### ISSUE TITLE
Op validation isn't working

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#56]
I think something changed in the schema for a job that I'm running but instead of getting a useful error it's just blowing up.

```
    TypeError: Arguments to path.join must be strings
        at getPath (/Users/kstaken/projects/opensource/teraslice/lib/utils/config.js:61:15)
        at initializeJob (/Users/kstaken/projects/opensource/teraslice/lib/utils/config.js:163:20)
        at Object.module.exports [as worker] (/Users/kstaken/projects/opensource/teraslice/lib/worker.js:10:16)
        at Domain.<anonymous> (/Users/kstaken/projects/opensource/terafoundation/index.js:120:25)
        at Domain.run (domain.js:197:16)
        at module.exports (/Users/kstaken/projects/opensource/terafoundation/index.js:44:13)
        at Object.<anonymous> (/Users/kstaken/projects/opensource/teraslice/service.js:6:43)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
```

**Comment by kstaken** [comment]
Digging further this is occurring when it tries to load the reporter. I have nothing in the configuration defining a reporter so it should just be ignored.

**Comment by kstaken** [comment]
Also, I had a parameter on an _op named incorrectly relative to the latest schema and just received a bunch of 'worker crashed' messages with no detail on what was wrong. I guessed what the problem was and corrected it then the error above started occurring. So it seems we've lost the useful messages when validation fails.
