### ISSUE TITLE
Shutdown isn't right when there is a startup error.

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#61]
Here it was having an issue connecting to remote services so the worker wasn't actually operational. The remote services were down. Trying to stop it resulted in it acting like it was doing work even though it really wasn't. It did eventually stop but this is incorrect behavior.

```
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":30,"msg":"Loading module kafka","time":"2015-09-15T22:14:54.609Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":30,"msg":"Using kafka zookeepers: r2s7.tera2.terascope.io:2181","time":"2015-09-15T22:14:54.611Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17861,"level":50,"msg":"Could not connect to Mongo DB: Error: failed to connect to [docker:27017]","time":"2015-09-15T22:14:54.738Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17861,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:54.740Z","v":0}
Elasticsearch ERROR: 2015-09-15T22:14:54Z
  Error: Request error, retrying -- connect ECONNREFUSED
      at Log.error (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/src/lib/transport.js:195:18)
      at HttpConnector.<anonymous> (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/src/lib/connectors/http.js:154:7)
      at ClientRequest.bound (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)
      at ClientRequest.emit (events.js:107:17)
      at Socket.socketErrorListener (_http_client.js:271:9)
      at Socket.emit (events.js:107:17)
      at net.js:459:14
      at process._tickDomainCallback (node.js:381:11)

{"name":"TeraSlice","hostname":"kteramac.local","pid":17860,"level":50,"msg":"Could not connect to Mongo DB: Error: failed to connect to [docker:27017]","time":"2015-09-15T22:14:54.757Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17860,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:54.760Z","v":0}
Elasticsearch WARNING: 2015-09-15T22:14:54Z
  Unable to revive connection: http://docker:9200/

Elasticsearch WARNING: 2015-09-15T22:14:54Z
  No living connections

{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":50,"msg":"Could not connect to Mongo DB: Error: failed to connect to [docker:27017]","time":"2015-09-15T22:14:54.793Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17862,"level":50,"msg":"Could not connect to Mongo DB: Error: failed to connect to [docker:27017]","time":"2015-09-15T22:14:54.793Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17862,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:54.796Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:54.796Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17861,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:55.006Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17860,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:55.022Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:55.056Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17862,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:55.062Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:55.076Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17861,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:55.456Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17860,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:55.461Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:55.496Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17862,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:55.502Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17860,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:56.206Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17861,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:56.206Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:56.238Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17862,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:56.244Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:56.333Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17860,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:57.466Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17861,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:57.466Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:57.496Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17862,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:57.502Z","v":0}
^C{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Shutting down.","time":"2015-09-15T22:14:57.841Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Notifying workers to stop.","time":"2015-09-15T22:14:57.841Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for 4 workers to stop.","time":"2015-09-15T22:14:57.841Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:58.466Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:14:58.844Z","v":0}
{"name":"job_logger","hostname":"kteramac.local","pid":17860,"level":30,"msg":"Worker: 2 , pid: 17860 is still processing. Will force shutdown in 60 seconds","time":"2015-09-15T22:14:58.847Z","v":0}
{"name":"job_logger","hostname":"kteramac.local","pid":17859,"level":30,"msg":"Worker: 1 , pid: 17859 is still processing. Will force shutdown in 60 seconds","time":"2015-09-15T22:14:58.847Z","v":0}
{"name":"job_logger","hostname":"kteramac.local","pid":17861,"level":30,"msg":"Worker: 3 , pid: 17861 is still processing. Will force shutdown in 60 seconds","time":"2015-09-15T22:14:58.847Z","v":0}
{"name":"job_logger","hostname":"kteramac.local","pid":17862,"level":30,"msg":"Worker: 4 , pid: 17862 is still processing. Will force shutdown in 60 seconds","time":"2015-09-15T22:14:58.848Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17860,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:59.601Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17861,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:59.601Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:59.627Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17862,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:14:59.635Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:14:59.844Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:00.843Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:01.845Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:02.087Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:02.844Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17860,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:03.225Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17861,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:03.225Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:03.248Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17862,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:03.256Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:03.845Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:04.845Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:05.845Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:06.847Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:07.847Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:08.237Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:08.848Z","v":0}
{"name":"job_logger","hostname":"kteramac.local","pid":17861,"level":30,"msg":"Worker: 3 , pid: 17861 is still processing. Will force shutdown in 50 seconds","time":"2015-09-15T22:15:08.872Z","v":0}
{"name":"job_logger","hostname":"kteramac.local","pid":17862,"level":30,"msg":"Worker: 4 , pid: 17862 is still processing. Will force shutdown in 50 seconds","time":"2015-09-15T22:15:08.872Z","v":0}
{"name":"job_logger","hostname":"kteramac.local","pid":17860,"level":30,"msg":"Worker: 2 , pid: 17860 is still processing. Will force shutdown in 50 seconds","time":"2015-09-15T22:15:08.872Z","v":0}
{"name":"job_logger","hostname":"kteramac.local","pid":17859,"level":30,"msg":"Worker: 1 , pid: 17859 is still processing. Will force shutdown in 50 seconds","time":"2015-09-15T22:15:08.876Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17860,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:09.377Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17861,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:09.377Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17859,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:09.400Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17862,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:09.404Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:09.849Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:10.849Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:11.850Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:12.851Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:13.853Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:14.853Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:15.854Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:16.856Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:17.856Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":50,"msg":"Error Error: Redis connection to docker:6379 failed - connect ECONNREFUSED","time":"2015-09-15T22:15:18.682Z","v":0}
{"name":"TeraSlice","hostname":"kteramac.local","pid":17858,"level":30,"msg":"Waiting for workers to stop: 4 pending.","time":"2015-09-15T22:15:18.856Z","v":0}
{"name":"job_logger","hostname":"kteramac.local","pid":17860,"level":30,"msg":"Worker: 2 , pid: 17860 is still processing. Will force shutdown in 40 seconds","time":"2015-09-15T22:15:18.902Z","v":0}
```

**Comment by jsnoble** [comment]
Is this still an issue?

**Comment by kstaken** [comment]
Not sure. I haven't seen it lately but also haven't explicitly tested this scenario.

**Comment by kstaken** [comment]
Still haven't seen this recently. Closing.
