### ISSUE TITLE
Cluster master failure when state cluster becomes inaccessible

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#632]
Obviously teraslice isn't very functional without the state cluster but currently if the state cluster is lost  and then comes back the cluster_master won't recover without intervention. 

When it gets into this state the API endpoint starts returning generic errors from Express.

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /txt/slicers</pre>
</body>
</html>
```

Ideally we figure out how to get Teraslice to basically pause and then resume when the cluster returns. 

There are various errors that show up in the logs along with the expected ES errors and timeouts.

```
TypeError: Cannot read property 'sockets' of undefined\n    at forwardMessage (/app/source/node_modules/teraslice/lib/cluster/services/messaging.js:346:19)\n    at Object.send (/app/source/node_modules/teraslice/lib/cluster/services/messaging.js:362:13)\n    at /app/source/node_modules/teraslice/lib/cluster/cluster_master.js:109:23
```

```
{"name":"teraslice","hostname":"node","pid":5001,"module":"elasticsearch_backend","level":40,"msg":"verifying job index is open","time":"2017-12-07T00:31:11.363Z","v":0}
{"name":"teraslice","hostname":"node","pid":5001,"module":"elasticsearch_backend","level":50,"msg":"Not all shards returned successful, shard errors:  node_not_connected_exception","time":"2017-12-07T00:31:11.961Z","v":0}
{"name":"teraslice","hostname":"node","pid":5001,"module":"elasticsearch_backend","level":40,"msg":"verifying job index is open","time":"2017-12-07T00:31:11.961Z","v":0}
{"name":"teraslice","hostname":"node","pid":5001,"module":"elasticsearch_backend","level":50,"msg":"Not all shards returned successful, shard errors:  node_not_connected_exception","time":"2017-12-07T00:31:12.965Z","v":0}
```

```
TypeError: Cannot read property 'emit' of undefined\n    at Object.broadcast (/app/source/node_modules/teraslice/lib/cluster/services/messaging.js:336:11)\n    at null._repeat (/app/source/node_modules/teraslice/lib/cluster/services/cluster/backends/native.js:151:19)\n    at wrapper [as _onTimeout] (timers.js:275:11)\n    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by jsnoble** [comment]
This is tied to https://github.com/terascope/elasticsearch_api/pull/6
