### ISSUE TITLE
execution_controller crash

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#675]
We're testing 0.29 with a kafka job. The job ran for a few minutes, processed a few hundred slices and then crashed with this error:

```
    "_failureReason": "TypeError: Cannot read property 'initialize' of undefined\n    at /app/source/node_modules/teraslice/lib/cluster/execution_controller/index.js:38:23\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:510:31)\n    at Promise._settlePromiseAt (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:584:18)\n    at Promise._settlePromises (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:700:14)\n    at Async._drainQueue (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"
```

**Comment by kstaken** [comment]
@ciorg also just encountered this same issue on his laptop. Here's a little more context. 

Something else that's weird about this is that the analytics is showing 8 steps in the job but the job really only has 4. It's likely this exception occurred after a failed slice.

```
[2018-03-12T18:16:05.163Z]  INFO: teraslice/30355 on charlies-MacBook-Pro.local: analytics for slice time : 5216,7,0,5224,0,0,0 size : 10,10,20,0,0,0,0 memory : 107104,829824,21712,77552,2040,3848,1848  (ex_id=756c4c7a-4273-4ec3-9ea7-fad6f05f02eb, job_id=b772b4aa-c662-41a5-a701-d182ed02a75a, module=slice, worker_id=172.29.1.118__37, slice_id=823e0961-2514-4902-8060-740178e8ec1a)
[2018-03-12T18:16:05.167Z] ERROR: teraslice/30353 on charlies-MacBook-Pro.local: Error in worker: 35 pid: 30353
[2018-03-12T18:16:05.167Z] ERROR: teraslice/30353 on charlies-MacBook-Pro.local: Cannot read property 'push' of undefined
[2018-03-12T18:16:05.167Z] ERROR: teraslice/30353 on charlies-MacBook-Pro.local:
   TypeError: Cannot read property 'push' of undefined
       at /Users/ciorg/Terascope/teraslice/lib/cluster/execution_controller/slice_analytics.js:20:39
       at Array.forEach (native)
       at Object.addStats (/Users/ciorg/Terascope/teraslice/lib/cluster/execution_controller/slice_analytics.js:19:19)
       at messaging.register.messaging.register.messaging.register.messaging.register.callback (/Users/ciorg/Terascope/teraslice/lib/cluster/execution_controller/engine.js:90:37)
       at Socket.<anonymous> (/Users/ciorg/Terascope/teraslice/lib/cluster/services/messaging.js:274:25)
       at emitOne (events.js:77:13)
       at Socket.emit (events.js:169:7)
       at /Users/ciorg/Terascope/teraslice/node_modules/socket.io/lib/socket.js:503:12
       at nextTickCallbackWith0Args (node.js:489:9)
       at process._tickDomainCallback (node.js:459:13)
[2018-03-12T18:16:05.776Z]  INFO: teraslice/29042 on charlies-MacBook-Pro.local: execution_controller has exited, id: 35, code: 255, signal: null
[2018-03-12T18:16:05.777Z] ERROR: teraslice/30355 on charlies-MacBook-Pro.local: worker 172.29.1.118__37 has disconnected from slicer ex_id 756c4c7a-4273-4ec3-9ea7-fad6f05f02eb transport close (ex_id=756c4c7a-4273-4ec3-9ea7-fad6f05f02eb, job_id=b772b4aa-c662-41a5-a701-d182ed02a75a, module=worker_executor, worker_id=172.29.1.118__37)
[2018-03-12T18:16:05.778Z]  INFO: teraslice/29042 on charlies-MacBook-Pro.local: launching a new execution_controller, id: 39
[2018-03-12T18:16:06.271Z] ERROR: teraslice/30359 on charlies-MacBook-Pro.local: Terminal error: shutting down execution 756c4c7a-4273-4ec3-9ea7-fad6f05f02eb, error: Slicer for ex_id: 756c4c7a-4273-4ec3-9ea7-fad6f05f02eb runtime error led to a restart, terminating execution with failed status, please use the recover api to return slicer to a consistent state (module=execution_controller, ex_id=756c4c7a-4273-4ec3-9ea7-fad6f05f02eb, job_id=b772b4aa-c662-41a5-a701-d182ed02a75a)
[2018-03-12T18:16:06.274Z] ERROR: teraslice/30359 on charlies-MacBook-Pro.local: (module=execution_controller, ex_id=756c4c7a-4273-4ec3-9ea7-fad6f05f02eb, job_id=b772b4aa-c662-41a5-a701-d182ed02a75a)
   Terminal error: shutting down execution 756c4c7a-4273-4ec3-9ea7-fad6f05f02eb, error: TypeError: Cannot read property 'initialize' of undefined
       at /Users/ciorg/Terascope/teraslice/lib/cluster/execution_controller/index.js:38:23
       at bound (domain.js:287:14)
       at runBound (domain.js:300:12)
       at tryCatcher (/Users/ciorg/Terascope/teraslice/node_modules/bluebird/js/main/util.js:26:23)
       at Promise._settlePromiseFromHandler (/Users/ciorg/Terascope/teraslice/node_modules/bluebird/js/main/promise.js:510:31)
       at Promise._settlePromiseAt (/Users/ciorg/Terascope/teraslice/node_modules/bluebird/js/main/promise.js:584:18)
       at Promise._settlePromises (/Users/ciorg/Terascope/teraslice/node_modules/bluebird/js/main/promise.js:700:14)
       at Async._drainQueue (/Users/ciorg/Terascope/teraslice/node_modules/bluebird/js/main/async.js:123:16)
       at Async._drainQueues (/Users/ciorg/Terascope/teraslice/node_modules/bluebird/js/main/async.js:133:10)
       at Immediate.Async.drainQueues [as _onImmediate] (/Users/ciorg/Terascope/teraslice/node_modules/bluebird/js/main/async.js:15:14)
       at processImmediate [as _immediateCallback] (timers.js:396:17)
[2018-03-12T18:16:06.274Z]  INFO: teraslice/30355 on charlies-MacBook-Pro.local: shutting down (module=state_storage)
[2018-03-12T18:16:06.275Z]  INFO: teraslice/30355 on charlies-MacBook-Pro.local: shutting down. (module=analytics_storage)
[2018-03-12T18:16:06.287Z]  INFO: teraslice/29042 on charlies-MacBook-Pro.local: execution_controller has exited, id: 39, code: 0, signal: null
[2018-03-12T18:16:06.310Z]  INFO: teraslice/30355 on charlies-MacBook-Pro.local: Flushed 4 records to index teracluster__analytics* (module=elasticsearch_backend)
[2018-03-12T18:16:07.276Z]  INFO: teraslice/30355 on charlies-MacBook-Pro.local: shutting down (ex_id=756c4c7a-4273-4ec3-9ea7-fad6f05f02eb, job_id=b772b4aa-c662-41a5-a701-d182ed02a75a, module=worker_executor, worker_id=172.29.1.118__37)
[2018-03-12T18:16:07.286Z]  INFO: teraslice/29042 on charlies-MacBook-Pro.local: worker has exited, id: 37, code: 0, signal: null
```

**Comment by kstaken** [comment]
Immediately after posting that, also got a failure again on the test job. It had processed over 12000 slices and then it appears to have gotten a broker timeout and hence a failed slice which caused the execution_controller to crash, restart and then the whole job to fail. 

```
    {"name":"teraslice","hostname":"r7c1n7.tera1.terascope.io","pid":442,"ex_id":"c293715c-3a84-4118-af44-5f721d52e240","job_id":"f2d9c80e-f4ff-4b03-a6ab-291209e749f7","module":"slice","worker_id":"10.210.0.104__21","slice_id":"441d3efb-18bd-480c-be06-d29e5e79218a","level":50,"msg":"An error has occurred: Error: Local: Broker transport failure\n    at Error (native), message:  { slice_id: '441d3efb-18bd-480c-be06-d29e5e79218a',\n  request: 1,\n  slicer_id: 0,\n  slicer_order: 12289,\n  _created: '2018-03-12T18:27:57.460Z' }","time":"2018-03-12T18:28:09.655Z","v":0}
r6c1n8.tera1.terascope.io:
    {"name":"teraslice","hostname":"r6c1n8.tera1.terascope.io","pid":736,"module":"execution_controller","ex_id":"c293715c-3a84-4118-af44-5f721d52e240","job_id":"f2d9c80e-f4ff-4b03-a6ab-291209e749f7","level":50,"msg":"Terminal error: shutting down execution c293715c-3a84-4118-af44-5f721d52e240, error: Slicer for ex_id: c293715c-3a84-4118-af44-5f721d52e240 runtime error led to a restart, terminating execution with failed status, please use the recover api to return slicer to a consistent state","time":"2018-03-12T18:28:18.107Z","v":0}
    {"name":"teraslice","hostname":"r6c1n8.tera1.terascope.io","pid":736,"module":"execution_controller","ex_id":"c293715c-3a84-4118-af44-5f721d52e240","job_id":"f2d9c80e-f4ff-4b03-a6ab-291209e749f7","level":50,"msg":"Terminal error: shutting down execution c293715c-3a84-4118-af44-5f721d52e240, error: TypeError: Cannot read property 'initialize' of undefined\n    at /app/source/node_modules/teraslice/lib/cluster/execution_controller/index.js:38:23\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:510:31)\n    at Promise._settlePromiseAt (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:584:18)\n    at Promise._settlePromises (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/promise.js:700:14)\n    at Async._drainQueue (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/teraslice/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)","time":"2018-03-12T18:28:18.114Z","v":0}
```
