### ISSUE TITLE
Errant stack traces when there is an error from elasticsearch

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#704]
The log entries below came from a job that attempted to run the `elasticsearch_reader` with `date_field_name` set to a field that doesn't exist in the mapping. Are these XHR errors a problem?

Also the warning on `max_result_window` seems out of place here as the value is `2,000,000`. I thought we were only triggering that warning if the value was set to the default. Really the logical thing would probably be to trigger it if it's below the requested size on the reader.

```
2018-05-14T21:33:18.495Z] ERROR: teraslice/85600 on kmacbook5.local: invoking elasticsearch_api _performSearch resulted in a runtime error: error: query_shard_exception No mapping found for [created2] in order to sort on on index: example-persistent (module=execution_engine, ex_id=71ee48c2-9d05-442b-b33f-065b542d9e96, job_id=507f1038-9e43-4d09-8bc0-c2596ed5ec51)
[2018-05-14T21:33:18.511Z]  WARN: teraslice/85600 on kmacbook5.local: max_result_window for index: example-persistent is set at 2000000 . On very large indices it is possible that a slice can not be divided to stay below this limit. If that occurs an error will be thrown by Elasticsearch and the slice can not be processed. Increasing max_result_window in the Elasticsearch index settings will resolve the problem. (module=execution_engine, ex_id=71ee48c2-9d05-442b-b33f-065b542d9e96, job_id=507f1038-9e43-4d09-8bc0-c2596ed5ec51)
[2018-05-14T21:33:18.531Z] ERROR: teraslice/85600 on kmacbook5.local: invoking elasticsearch_api _performSearch resulted in a runtime error: error: query_shard_exception No mapping found for [created2] in order to sort on on index: example-persistent (module=execution_engine, ex_id=71ee48c2-9d05-442b-b33f-065b542d9e96, job_id=507f1038-9e43-4d09-8bc0-c2596ed5ec51)
[2018-05-14T21:33:18.532Z] ERROR: teraslice/85600 on kmacbook5.local: Could not initialize slicers, error: invoking elasticsearch_api _performSearch resulted in a runtime error: error: query_shard_exception No mapping found for [created2] in order to sort on on index: example-persistent (module=execution_engine, ex_id=71ee48c2-9d05-442b-b33f-065b542d9e96, job_id=507f1038-9e43-4d09-8bc0-c2596ed5ec51)
[2018-05-14T21:33:18.550Z] ERROR: teraslice/85595 on kmacbook5.local: terminal error for execution: 71ee48c2-9d05-442b-b33f-065b542d9e96, shutting down execution (module=native_cluster_service)
[2018-05-14T21:33:18.553Z]  INFO: teraslice/85600 on kmacbook5.local: shutting asset store down. (module=assets_storage)
[2018-05-14T21:33:18.554Z]  INFO: teraslice/85600 on kmacbook5.local: shutting down (module=state_storage)
[2018-05-14T21:33:18.554Z]  INFO: teraslice/85601 on kmacbook5.local: shutting asset store down. (module=assets_storage)
[2018-05-14T21:33:18.554Z]  INFO: teraslice/85602 on kmacbook5.local: shutting asset store down. (module=assets_storage)
[2018-05-14T21:33:18.554Z]  INFO: teraslice/85601 on kmacbook5.local: shutting down (module=state_storage)
[2018-05-14T21:33:18.554Z]  INFO: teraslice/85601 on kmacbook5.local: shutting down. (module=analytics_storage)
[2018-05-14T21:33:18.554Z]  INFO: teraslice/85602 on kmacbook5.local: shutting down (module=state_storage)
[2018-05-14T21:33:18.555Z]  INFO: teraslice/85602 on kmacbook5.local: shutting down. (module=analytics_storage)
[2018-05-14T21:33:18.555Z]  INFO: teraslice/85600 on kmacbook5.local: shutting down. (module=ex_storage)
[2018-05-14T21:33:18.556Z]  INFO: teraslice/85600 on kmacbook5.local: slicer for execution: 71ee48c2-9d05-442b-b33f-065b542d9e96 has received a shutdown notice (module=execution_engine, ex_id=71ee48c2-9d05-442b-b33f-065b542d9e96, job_id=507f1038-9e43-4d09-8bc0-c2596ed5ec51)
[2018-05-14T21:33:18.572Z]  INFO: teraslice/85593 on kmacbook5.local: execution_controller has exited, id: 3, code: 0, signal: null
[2018-05-14T21:33:18.574Z] ERROR: teraslice/85601 on kmacbook5.local: (ex_id=71ee48c2-9d05-442b-b33f-065b542d9e96, job_id=507f1038-9e43-4d09-8bc0-c2596ed5ec51, module=worker_executor, worker_id=127.0.0.1__4)
    Error in worker socket, error: Error: xhr poll error
        at XHR.Transport.onError (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:64:13)
        at Request.<anonymous> (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:128:10)
        at Request.Emitter.emit (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
        at Request.onError (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:309:8)
        at null._onTimeout (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:256:18)
        at Timer.listOnTimeout (timers.js:92:15)
[2018-05-14T21:33:18.574Z] ERROR: teraslice/85602 on kmacbook5.local: (ex_id=71ee48c2-9d05-442b-b33f-065b542d9e96, job_id=507f1038-9e43-4d09-8bc0-c2596ed5ec51, module=worker_executor, worker_id=127.0.0.1__5)
    Error in worker socket, error: Error: xhr poll error
        at XHR.Transport.onError (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:64:13)
        at Request.<anonymous> (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:128:10)
        at Request.Emitter.emit (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
        at Request.onError (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:309:8)
        at null._onTimeout (/Users/kstaken/projects/opensource/test/teraslice/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:256:18)
        at Timer.listOnTimeout (timers.js:92:15)
[2018-05-14T21:33:19.557Z]  INFO: teraslice/85602 on kmacbook5.local: shutting down (ex_id=71ee48c2-9d05-442b-b33f-065b542d9e96, job_id=507f1038-9e43-4d09-8bc0-c2596ed5ec51, module=worker_executor, worker_id=127.0.0.1__5)
[2018-05-14T21:33:19.557Z]  INFO: teraslice/85601 on kmacbook5.local: shutting down (ex_id=71ee48c2-9d05-442b-b33f-065b542d9e96, job_id=507f1038-9e43-4d09-8bc0-c2596ed5ec51, module=worker_executor, worker_id=127.0.0.1__4)
[2018-05-14T21:33:19.577Z]  INFO: teraslice/85593 on kmacbook5.local: worker has exited, id: 4, code: 0, signal: null
[2018-05-14T21:33:19.577Z]  INFO: teraslice/85593 on kmacbook5.local: worker has exited, id: 5, code: 0, signal: null
```

**Comment by kstaken** [comment]
Not sure this is still relevant. Closing.
