### ISSUE TITLE
Unable to add workers with native clustering in kubernetes

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#728]
Starts up ok with v0.35.0.  The master produces these results in v0.36.2.  It can start up fine with 0 workers but will go into this error loop once workers are added.

Here is [reference to offending line](https://github.com/terascope/teraslice/blob/v0.36.2/lib/cluster/services/cluster/backends/native.js#L110) but I suspect it's more of a symptom.

```
18:49:38.254Z  INFO teraslice: node has successfully connected to: http://teraslice-qa1:5678 (module=node_master)
18:49:38.258Z  WARN teraslice: (module=node_master)
    Attempting to connect to cluster_master: http://teraslice-qa1:5678 { Error: xhr post error
        at XHR.Transport.onError (/app/source/node_modules/teraslice/node_modules/engine.io-client/lib/transport.js:64:13)
        at Request.<anonymous> (/app/source/node_modules/teraslice/node_modules/engine.io-client/lib/transports/polling-xhr.js:109:10)
        at Request.Emitter.emit (/app/source/node_modules/teraslice/node_modules/component-emitter/index.js:133:20)
        at Request.onError (/app/source/node_modules/teraslice/node_modules/engine.io-client/lib/transports/polling-xhr.js:309:8)
        at Timeout._onTimeout (/app/source/node_modules/teraslice/node_modules/engine.io-client/lib/transports/polling-xhr.js:256:18)
        at ontimeout (timers.js:482:11)
        at tryOnTimeout (timers.js:317:5)
        at Timer.listOnTimeout (timers.js:277:5) type: 'TransportError', description: 503 }
18:49:38.260Z  INFO teraslice: node has disconnected from: http://teraslice-qa1:5678 (module=node_master)
18:49:38.264Z ERROR teraslice: Error in worker: 26 pid: 266
18:49:38.264Z ERROR teraslice: Cannot read property 'active' of undefined
18:49:38.265Z ERROR teraslice:
    TypeError: Cannot read property 'active' of undefined
        at callback (/app/source/node_modules/teraslice/lib/cluster/services/cluster/backends/native.js:110:38)
        at Socket.socket.on (/app/source/node_modules/teraslice/lib/cluster/services/messaging.js:282:25)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at Socket.emit (/app/source/node_modules/teraslice/node_modules/socket.io/lib/socket.js:142:10)
        at Socket.onclose (/app/source/node_modules/teraslice/node_modules/socket.io/lib/socket.js:454:8)
        at Client.onclose (/app/source/node_modules/teraslice/node_modules/socket.io/lib/client.js:254:24)
        at emitTwo (events.js:131:20)
        at Socket.emit (events.js:214:7)
        at Socket.onClose (/app/source/node_modules/teraslice/node_modules/engine.io/lib/socket.js:318:10)
        at Object.onceWrapper (events.js:313:30)
        at emitNone (events.js:106:13)
        at XHR.emit (events.js:208:7)
        at XHR.Transport.onClose (/app/source/node_modules/teraslice/node_modules/engine.io/lib/transport.js:127:8)
        at XHR.Polling.onClose (/app/source/node_modules/teraslice/node_modules/engine.io/lib/transports/polling.js:225:31)
        at callback (/app/source/node_modules/teraslice/node_modules/engine.io/lib/transports/polling.js:204:12)
18:49:38.875Z  INFO teraslice: cluster_master has exited, id: 26, code: 255, signal: null
18:49:38.879Z  INFO teraslice: launching a new cluster_master, id: 27
```

**Comment by erik-stephens** [comment]
I can reproduce in v0.35.0 as well.  If I start with 0 workers and then add them later, then it works.  Doing similar in v0.36.2 didn't work around the problem.

**Comment by erik-stephens** [comment]
Looking like user error: I had api requests going to all nodes, not just the master.  I'll close once I confirm that I can't reproduce with v0.36.2.

**Comment by erik-stephens** [comment]
v0.36.2 has been exonerated.
