### ISSUE TITLE
native_cluster_service shutdown on ES logging error

### ISSUE THREAD

**Issue by jeffmontagna** [terascope/teraslice#746]
If there is an error in logging to elasticsearch the `native_cluster_service` can shutdown. The versions used in the testing were `0.35.0` and `0.36.4`.  Both had the same results, api not available after failed log attempts to elasticsearch.  Also tested in another dev instance with version `0.36.4`, and logging worked as expected.  

Submitted job with an error multiple times, expected to see errors in log file and in elasticsearch.  I never saw the logging index get created in elasticsearch.  What did happen is shortly after the submitting the job the api would shutdown.
```
(py3-dev) balor:inwork montaj1$ curl -sS -XPOST skippy1:5678/jobs -d@data_generator_error.json
{
    "error": 500,
    "message": "Job submission failed, error: Error validating job: Error: Could not retrieve code for: xelasticsearch_index_selector , error message: Error: Cannot find module 'xelasticsearch_index_selector'"
}(py3-dev) balor:inwork montaj1$ curl -sS -XPOST skippy1:5678/jobs -d@data_generator_error.json

```
Error Message:
```
(py3-dev) balor:inwork montaj1$ curl -sS -XPOST skippy1:5678/jobs -d@data_generator_error.json
{"error":"api is not available"}
```

terafoundation config:
```
terafoundation:
    environment: 'production'
    log_path: '/app/logs'
.
.
# Logging Configuration (terafoundation)
    log_level:
        - elasticsearch: 'error'
        - file: 'info'
    logging:
        - elasticsearch
        - file
    logging_connection: es_util1
```    

Error from teraslice.log where api shutdown over the weekend:
```
{
  "name": "teraslice",
  "hostname": "merlin.io",
  "pid": 16,
  "module": "native_cluster_service",
  "level": 50,
  "msg": "terminal error for execution: 1c548c61-95d2-4d2e-8671-d7e93fbf1c90, shutting down execution",
  "time": "2018-06-16T07:57:34.008Z",
  "v": 0
}
```

syslog:
```
root@merlin1:/var/log# zgrep "Log.error" syslog.3.gz
syslog.3.gz:Jun 16 07:52:00 merlin.io systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:52:00 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:52:00 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:52:00 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:52:00 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:52:00 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:52:00 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:52:00 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:53:04 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:53:04 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:53:04 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:53:04 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:53:04 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:53:04 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:53:04 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:53:04 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:54:05 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:54:05 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:54:05 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:54:05 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:54:05 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:54:05 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:54:05 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:54:05 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:55:09 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:55:09 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:55:09 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:55:09 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:55:09 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:55:09 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:55:09 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:55:09 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:56:13 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:56:13 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:56:13 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:56:13 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:56:13 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:56:13 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:56:13 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:56:13 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:57:14 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:57:14 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:57:14 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:57:14 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:57:14 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:57:14 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:57:14 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:57:14 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:58:33 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:58:33 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:58:33 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
syslog.3.gz:Jun 16 07:58:33 merlin1 systemd-docker[10547]:       at Log.error (/app/source/node_modules/teraslice/node_modules/elasticsearch/src/lib/log.js:225:56)
```

**Comment by peterdemartini** [comment]
This might be fixed, can you verify this @jeffmontagna?

**Comment by kstaken** [comment]
No further reports on this so considering it resolved.
