### ISSUE TITLE
In kubernetes mode, jobs requiring assets get stuck in init

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#760]
The workers show the following error:

```
[2018-07-13T22:43:02.346Z]  INFO: teraslice/1 on teraslice-worker-94cd762d-8e51-4c8c-82be-923d78c83972-7bfbz8zg8: launching a new assets_loader, id: 463
[2018-07-13T22:43:02.910Z] ERROR: teraslice/2792 on teraslice-worker-94cd762d-8e51-4c8c-82be-923d78c83972-7bfbz8zg8: Error in worker: 463 pid: 2792
[2018-07-13T22:43:02.911Z] ERROR: teraslice/2792 on teraslice-worker-94cd762d-8e51-4c8c-82be-923d78c83972-7bfbz8zg8: Unexpected token u in JSON at position 0
[2018-07-13T22:43:02.914Z] ERROR: teraslice/2792 on teraslice-worker-94cd762d-8e51-4c8c-82be-923d78c83972-7bfbz8zg8:
    SyntaxError: Unexpected token u in JSON at position 0
        at JSON.parse (<anonymous>)
        at Object.assetLoader [as assets_loader] (/app/source/lib/cluster/assets_loader.js:20:22)
        at _.forOwn (/app/source/node_modules/terafoundation/index.js:72:32)
        at /app/source/node_modules/lodash/lodash.js:4925:15
        at baseForOwn (/app/source/node_modules/lodash/lodash.js:3010:24)
        at Function.forOwn (/app/source/node_modules/lodash/lodash.js:13013:24)
        at findWorkerCode (/app/source/node_modules/terafoundation/index.js:69:15)
        at Domain.primary.run (/app/source/node_modules/terafoundation/index.js:159:13)
        at Domain.run (domain.js:242:14)
        at module (/app/source/node_modules/terafoundation/index.js:89:13)
        at Object.<anonymous> (/app/source/service.js:38:26)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
```

The asset loads fine:

```
curl -Ss 10.0.0.5:30678/txt/assets
name               version  id                                        _created                  description
-----------------  -------  ----------------------------------------  ------------------------  ------------------------------
common_processors  0.0.40   37a36fdd3de8977f7641b36bd0e319c34500d6b6  2018-07-13T22:19:27.420Z  Processing modules that are us
```

The sample job is:

```
{
    "name": "gen-tenk-noop",
    "lifecycle": "persistent",
    "workers": 10,
    "assets": ["common_processors"],
    "operations": [
        {
            "_op": "elasticsearch_data_generator",
            "json_schema": "",
            "size": 10000,
            "start": "",
            "end": "",
            "format": "",
            "stress_test": false,
            "date_key": "created",
            "set_id": "",
            "id_start_key": ""
        },
        {
            "_op": "drop_property",
            "property": "userAgent"
        },
        {
            "_op": "noop"
        }
    ],
    "analytics": true
}
```

And is confirmed to work on an internal multinode cluster.

**Comment by jsnoble** [comment]
this looks like because the process looks at the process enviroment to get the things it needs. Namely the job and other identifiers which is not how it is used in kubernetes

**Comment by godber** [comment]
I control the environment the workers run in, so if I knew what env variables had to be set I could do that.  I'll dig them out of the code when I get back if clues don't magically appear here.  So it can probably work the same way, I just need to modify the deployment that launches the processes (pods).

**Comment by godber** [comment]
Looks like `assets_loader.js` needs the following:

* `process.env.job` - [L20](https://github.com/terascope/teraslice/blob/master/lib/cluster/assets_loader.js#L20)
* `process.env.__msgId` - [L72](https://github.com/terascope/teraslice/blob/master/lib/cluster/assets_loader.js#L72)
* `process.env.preload` - [L79](https://github.com/terascope/teraslice/blob/master/lib/cluster/assets_loader.js#L79)

So I just need to figure out what these should be set to.

Looks like these get set in the asset loader's process context in the [`node_master.js`](https://github.com/terascope/teraslice/blob/master/lib/cluster/node_master.js#L70-L81)

**Comment by godber** [comment]
There is kind of a broader question which is what I think Jared was alluding to when he said "not how it is used in kubernetes" ... that is, how should assets work in k8s.  There are two options:

1. make the `assets_loader.js` work in the k8s environment
1. change the deployments so that they include a shared volume of some sort

I suspect we'd want both in the long term.  It may be quick to fix the first option since it's probably mostly a matter of setting the proper environment when I launch workers.  The second option requires that the users k8s cluster support some sort of shared file system which is a higher bar for the user to achieve.

**Comment by godber** [comment]
The new worker in the project https://github.com/terascope/teraslice-worker will load assets correctly.

**Comment by godber** [comment]
Until further notice we're going to abandon the original worker when using the k8s cluster mode.  So this ticket will be closed without this issue being resolved.  Maybe something will cause us to come back to the original worker and resolve the issue outlined here.

**Comment by godber** [comment]
refs: #764
