### ISSUE TITLE
Doesn't properly recover if elasticsearch is not running

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#765]
Teraslice doesn't properly recover if elasticsearch goes away and comes back. While elasticsearch is down it will throw the expected `No living connections` error but once it comes back it starts logging the following message repeatedly.

```
ttempting to connect to elasticsearch: {\"connection\":\"default\"}, error: TypeError: Cannot read property 'shards' of undefined\n    at _createIndex.then.then (/Users/kstaken/projects/opensource/teraslice/lib/cluster/storage/backends/elasticsearch_store.js:356:51)\n    at bound (domain.js:301:14)\n    at runBound (domain.js:314:12)\n    at tryCatcher (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by jsnoble** [comment]
Could not duplicate, and we have not really seen this issue since
