### ISSUE TITLE
teraslice-cli issues

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#874]
Getting these into a ticket so that we can review. Some of these should probably be broken out into separate tickets.

--cluster-manager-type -- this option can be removed as this information is now exposed on the root URL of Teraslice and can be introspected.

Options on sub commands -- when you get the options on sub commands many of them do not apply to the current context and should not be displayed.

Examples
     * some examples still hard code the command name
     * some commands are missing examples

Not enough non-option arguments: got 0, need at least 1 
    * this message is pretty unclear on what it wants. Especially on the commands where examples are missing.

cluster_sh -- There is confusion over cluster_sh and object_ids. In most cases where the commands reference cluster_sh they really mean object_id.

earl ex list -- should not be restricted to running/failing by default, nor should any other command. Filtering by status should be an option and if there is a common set of statuses then maybe special flags can be added for those cases.

earl jobs run -- the mechanism for specifying the cluster when providing the jobs file is not correct
     * You can do `earl jobs run localhost:job.json`
     * But then you can not do `earl jobs stop localhost:job.json` which is completely inconsistent
     * I think it's a bad idea to muddle the cluster_sh, object_id with the job.json handling. 
     * This implies that when you're working with a job.json then you have to specify the cluster independently. We should discuss.

earl jobs run -- Doesn't add metadata to the job. Open for discussion if it should. tjm did.

earl jobs stop -- should not prompt for confirmation when stopping a single job.
     
earl jobs --
     - Commands that take .json files should not require the file extension
     - The documentation is still written from the perspective of 'all' jobs

earl jobs find -- no idea how to use this command. I question if it should exist until we have a stable base.

earl assets list -- this command doesn't exist but should

earl assets deploy -- does not appear to add the meta data to assets.json

earl aliases update -- it appears re-running add has the same behavior as update. 

earl ex errors localhost --
```
UncaughtException:  TypeError: tsuFunctions.errors is not a function
    at Object.exports.handler (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/cmds/ex/errors.js:37:25)
    at Object.runCommand (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/yargs.js:1059:30)
    at Object.runCommand (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/lib/command.js:198:45)
    at Object.parseArgs [as _parseArgs] (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/index.js:5:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

earl jobs init --
```
UncaughtException:  TypeError: Cannot read property 'indexOf' of undefined
    at _urlCheck (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/cmds/lib/config.js:176:19)
    at getClusterHost (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/cmds/lib/config.js:117:26)
    at Object.returnConfigData (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/cmds/lib/config.js:96:81)
    at Object.exports.handler (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/cmds/jobs/init.js:17:36)
    at Object.runCommand (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/yargs.js:1059:30)
    at Object.runCommand (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/lib/command.js:198:45)
    at Object.parseArgs [as _parseArgs] (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/Users/kstaken/projects/opensource/teraslice/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/kstaken/projects/opensource/teraslice/packages/teraslice-cli/index.js:5:18
```

**Comment by kstaken** [comment]
refs #843

**Comment by kstaken** [comment]
These have been addressed.
