### ISSUE TITLE
Don't die if assets dir already exists

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#875]
Strange that `fse.ensureDir()` throws if already exists:

```bash
curl -sS -X POST ts-prod1/jobs/d3bdd26e-ba26-4e2f-a073-df67b7dc488c/_start | jq -r .message
Could not start job: d3bdd26e-ba26-4e2f-a073-df67b7dc488c, error: could not start job, error: Error: Failure to get assets, caused by Error: Failure to the ensure assets directory /app/assets/, for reason EEXIST: file already exists, mkdir '/app/assets'
    at fse.ensureDir.catch (/app/source/packages/teraslice/lib/cluster/storage/assets.js:211:31)
    at <anonymous>
    at ChildProcess.child.on (/app/source/packages/teraslice/lib/workers/assets/spawn.js:38:31)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by erik-stephens** [comment]
Couldn't duplicate with a quick test in the REPL.  We think this was related to remote storage issue at the time.
