### ISSUE TITLE
Elasticsearch 2.1 search size limit

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#96]
Elasticsearch 2.1 has started enforcing a 10,000 result default size on search requests. This can be increased on a per index basis but in most cases the default will be in effect. When the limit is hit ES errors and rejects the query.

```
{"name":"job_logger","hostname":"kteramac.local","pid":56983,"level":50,"msg":"An error has occured: Error: [query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [116088]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.\n    at respond (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/src/lib/transport.js:256:15)\n    at checkRespForFailure (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/src/lib/transport.js:219:7)\n    at keepAliveConnector.<anonymous> (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)\n    at IncomingMessage.wrapper (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickDomainCallback (node.js:381:11) \n on message:  { start: '2014-05-06T13:10:55+00:00',\n  end: '2014-05-06T13:10:56+00:00',\n  count: 116088 }","time":"2015-12-21T19:18:18.536Z","v":0}
```

We're going to have to work around this limit. Jobs will need knowledge of what limit is in effect and will need to restrict all data retrieval to be less than the limit. If the admin increases the limit on the index then the job can use a larger limit otherwise it will need to work within the 10,000 record default limit.

**Comment by kstaken** [comment]
addressed in #98
