### ISSUE TITLE
Zombie job after fatal bulk error?

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#984]
While inspecting possible stuck workers, this was something new to me.  Wasn't stuck - fatal error in bulk insert should've killed it but it didn't?
```
kubectl -n ts-prod1 logs teraslice-worker-02ec76de-8ea1-42f7-8a22-0510f90639c0-6cb8srssq --tail 10 | bunyan -o short
03:35:08.491Z  INFO worker: analytics for slice: slice_id: "24d2bfe5-0400-4dc1-8b5f-be1d9adfd741", slicer_id: 0, slicer_order: 28, _created: "2019-01-26T03:25:03.657Z", time: [300404, 0, 0, 0, 0], memory: [609344, 4096, 6992, 3104, 4672], size: [0, 0, 0, 0, 0] (ex_id=02ec76de-8ea1-42f7-8a22-0510f90639c0, job_id=9beddd74-edcf-48f0-9ea7-100d577f59ee, module=slice, assignment=worker, slice_id=24d2bfe5-0400-4dc1-8b5f-be1d9adfd741)
03:35:08.491Z  INFO worker: slice complete for execution 02ec76de-8ea1-42f7-8a22-0510f90639c0 (ex_id=02ec76de-8ea1-42f7-8a22-0510f90639c0, job_id=9beddd74-edcf-48f0-9ea7-100d577f59ee, module=worker, assignment=worker)
03:37:15.977Z ERROR worker: (module=elasticsearch_backend)
    invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
03:37:15.977Z ERROR worker: (module=elasticsearch_backend)
    bulk sender error: invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
03:37:15.977Z ERROR worker: (module=elasticsearch_backend)
    bulk sender error: invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
03:37:15.980Z FATAL worker: (module=worker:shutdown_handler)
    worker received an unhandledRejection, exiting in 300000ms... Error: bulk sender error: invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
        at elasticsearch.bulkSend.then.catch (/app/source/packages/teraslice/lib/cluster/storage/backends/elasticsearch_store.js:225:43)
        at tryCatcher (/app/source/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/app/source/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/app/source/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/app/source/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/app/source/node_modules/bluebird/js/release/promise.js:690:18)
        at _drainQueueStep (/app/source/node_modules/bluebird/js/release/async.js:138:12)
        at _drainQueue (/app/source/node_modules/bluebird/js/release/async.js:131:9)
        at Async._drainQueues (/app/source/node_modules/bluebird/js/release/async.js:147:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/app/source/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:810:20)
        at tryOnImmediate (timers.js:768:5)
        at processImmediate [as _immediateCallback] (timers.js:745:5)
03:37:15.980Z  WARN worker: worker shutdown was called for execution 02ec76de-8ea1-42f7-8a22-0510f90639c0 (ex_id=02ec76de-8ea1-42f7-8a22-0510f90639c0, job_id=9beddd74-edcf-48f0-9ea7-100d577f59ee, module=worker, assignment=worker)
03:40:08.951Z  INFO worker: Resolving with 0 results (module=operation, opName=teraslice_kafka_reader, jobName=s4-networks_key_cell-store-kafka, jobId=9beddd74-edcf-48f0-9ea7-100d577f59ee, exId=02ec76de-8ea1-42f7-8a22-0510f90639c0)
03:42:08.951Z ERROR worker: (module=elasticsearch_backend)
    invoking elasticsearch-api _runRequest resulted in a runtime error: Error: Request Timeout after 120000ms
        at /app/source/node_modules/elasticsearch/src/lib/transport.js:354:15
        at Timeout.<anonymous> (/app/source/node_modules/elasticsearch/src/lib/transport.js:383:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)
03:42:13.981Z  INFO worker: worker shutdown took 298001ms (module=worker:shutdown_handler)
```

but it survives:
```
kubectl -n ts-prod1 exec teraslice-worker-02ec76de-8ea1-42f7-8a22-0510f90639c0-6cb8srssq -- date
Sat Jan 26 03:50:51 UTC 2019
```

**Comment by kstaken** [comment]
refs #987

**Comment by peterdemartini** [comment]
In this scenario, the worker should have automatically restarted by k8s, which means the pod would have the same name on restart? If this happens again, it may be more useful to run `uptime` on the pod instead of `date`?

**Comment by godber** [comment]
I know you guys have worked this out behind the scenes ... but I just checked and the pods report the host uptime, not their uptime.  Calling `kubectl describe pod ...` would probably be better.

**Comment by kstaken** [comment]
I believe the top level issue here is resolved but the comments imply there may still be a change needed somewhere. If so maybe it needs a new ticket.

**Comment by kstaken** [comment]
This should be resolved in v54
